export type ComponentCategory =
  | "animated"
  | "primitives"
  | "charts"
  | "widgets"
  | "buttons"
  | "backgrounds";

export type DisplayStrategy = "center" | "fullscreen" | "cover" | "fit" | "auto";

export interface PropDefinition {
  name: string;
  type: "string" | "number" | "boolean" | "select" | "color";
  default?: string | number | boolean;
  description: string;
  required: boolean;
  options?: string[];       // for "select" type
  min?: number;            // for "number" type
  max?: number;            // for "number" type
  step?: number;           // for "number" type
}

export interface ComponentVariant {
  name: string;
  props: Record<string, unknown>;
}

export interface RegistryEntry {
  name: string;
  slug: string;
  category: ComponentCategory;
  description: string;
  dependencies: string[];
  packagePath: string;       // path inside packages/ui/src (kept for backward compat)
  files: string[];           // all source files relative to packages/ui/src/ (shadcn registry)
  propDefs?: PropDefinition[]; // tweakable props for the Props Tweaker panel
  variants?: ComponentVariant[];
  presentationStrategy?: DisplayStrategy;
}

export const registry: RegistryEntry[] = [
  {
    name: "Infinite Scroll",
    slug: "infinite-scroll",
    category: "animated",
    description: "Seamless infinite fullscreen scroll with parallax image effects, powered by Lenis smooth scrolling and GSAP scrub animations.",
    dependencies: ["gsap", "lenis"],
    packagePath: "animated/InfiniteScroll.tsx",
    files: ["animated/InfiniteScroll.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "parallaxPercent", type: "number", default: 50, description: "Parallax vertical offset percentage", required: false, min: 0, max: 100, step: 5 },
      { name: "snapDuration", type: "number", default: 0.9, description: "Snap animation duration in seconds", required: false, min: 0.3, max: 2, step: 0.1 },
      { name: "showProgress", type: "boolean", default: true, description: "Show a minimal dot progress indicator at the bottom", required: false },
      { name: "showLabels", type: "boolean", default: true, description: "Show slide label and caption overlays", required: false },
      { name: "showScrollCue", type: "boolean", default: true, description: "Show a 'Scroll' hint on the first slide", required: false },
      { name: "overlayOpacity", type: "number", default: 0.55, description: "Dark overlay gradient opacity (0 to 1)", required: false, min: 0, max: 1, step: 0.05 },
    ],
  },
  {
    name: "Image Reveal",
    slug: "image-reveal",
    category: "animated",
    description: "An image reveal effect using diagonal stripes masking and sliding clip-paths.",
    dependencies: ["framer-motion"],
    packagePath: "animated/ImageReveal.tsx",
    files: ["animated/ImageReveal.tsx"],
  },
  {
    name: "Image Parallax",
    slug: "image-parallax",
    category: "animated",
    description: "A smooth mouse-move and scroll-driven parallax image perspective effect.",
    dependencies: ["framer-motion"],
    packagePath: "animated/ImageParallax.tsx",
    files: ["animated/ImageParallax.tsx"],
  },
  {
    name: "Living Text",
    slug: "living-text",
    category: "animated",
    description: "Stretches, rotates, and pushes characters dynamically based on real-time cursor proximity.",
    dependencies: ["framer-motion"],
    packagePath: "animated/LivingText.tsx",
    files: ["animated/LivingText.tsx"],
    propDefs: [
      { name: "text", type: "string", default: "LIVING TEXT", description: "Text content to animate", required: true },
      { name: "radius", type: "number", default: 170, description: "Cursor influence radius in px", required: false, min: 50, max: 400, step: 10 },
      { name: "strength", type: "number", default: 46, description: "Movement offset strength in px", required: false, min: 5, max: 120, step: 1 },
      { name: "mode", type: "select", default: "all", description: "Proximity interaction mode", required: false, options: ["repel", "magnetize", "stretch", "rotate", "ripple", "all"] },
      { name: "liquify", type: "boolean", default: true, description: "Apply SVG turbulence liquification filter", required: false },
    ],
  },
  {
    name: "Spotlight Text",
    slug: "spotlight-text",
    category: "animated",
    description: "Debossed display text with a cursor-following golden spotlight clipped to glyph shapes. Auto-detects i/j ascender dots as glowing bulbs.",
    dependencies: [],
    packagePath: "animated/spotlight-text/SpotlightText.tsx",
    files: [
      "animated/spotlight-text/index.ts",
      "animated/spotlight-text/SpotlightText.tsx",
      "animated/spotlight-text/types.ts",
      "animated/spotlight-text/themes.ts",
      "animated/spotlight-text/hooks/useSpotlightCursor.ts",
    ],
    presentationStrategy: "center",
    variants: [
      { name: "Light", props: { text: "Antimetal", theme: "light" } },
      { name: "Dark", props: { text: "Antimetal", theme: "dark" } },
    ],
    propDefs: [
      { name: "text", type: "string", default: "Antimetal", description: "Text content to render", required: true },
      { name: "theme", type: "select", default: "light", description: "Surface and glow palette", required: false, options: ["light", "dark"] },
      { name: "spotlightRadius", type: "number", default: 120, description: "Spotlight radius in px", required: false, min: 60, max: 300, step: 10 },
      { name: "fontWeight", type: "number", default: 800, description: "Font weight", required: false, min: 400, max: 900, step: 100 },
      { name: "showBulb", type: "boolean", default: true, description: "Show glowing bulbs on i/j dots", required: false },
    ],
  },
  {
    name: "Gravity Card Stack",
    slug: "gravity-card-stack",
    category: "animated",
    description: "Falling rigid body physics cards container that reacts to scroll triggers.",
    dependencies: ["matter-js", "gsap"],
    packagePath: "animated/GravityCardStack.tsx",
    files: ["animated/GravityCardStack.tsx"],
  },
  {
    name: "Morphing Nav",
    slug: "morphing-nav",
    category: "animated",
    description: "An interactive navigation bar with liquid morphing SVG background shapes.",
    dependencies: ["framer-motion", "lucide-react"],
    packagePath: "animated/MorphingNav.tsx",
    files: ["animated/MorphingNav.tsx"],
  },
  {
    name: "Coverflow Carousel",
    slug: "coverflow-carousel",
    category: "animated",
    description: "A hardware-accelerated 3D coverflow carousel with continuous modular perspective transforms and comprehensive gesture tracking.",
    dependencies: ["framer-motion"],
    packagePath: "animated/coverflow/CoverflowCarousel.tsx",
    files: [
      "animated/coverflow/CoverflowCarousel.tsx",
      "animated/coverflow/CoverflowCard.tsx",
      "animated/coverflow/types.ts",
      "animated/coverflow/utils.ts",
      "animated/coverflow/useCoverflow.ts",
    ],
  },
  {
    name: "Void Button",
    slug: "void-button",
    category: "buttons",
    description: "Pure black button that reveals a luxury gold gradient under the cursor via a smooth radial mask.",
    dependencies: ["framer-motion"],
    packagePath: "animated/VoidButton.tsx",
    files: ["animated/VoidButton.tsx"],
    propDefs: [
      { name: "variant", type: "select", default: "ambient", description: "Button style variant", required: false, options: ["ambient", "neon-edge", "metallic-sheen", "glassmorphic", "cyber-laser", "classic-gold"] },
      { name: "children", type: "string", default: "Void Button", description: "Button text label", required: false },
      { name: "disabled", type: "boolean", default: false, description: "Disable button state", required: false }
    ],
  },
  {
    name: "Brushed Titanium Button",
    slug: "brushed-titanium-button",
    category: "buttons",
    description: "Machined titanium texture with anisotropic highlight sweeps and reactive spotlight illumination.",
    dependencies: ["framer-motion"],
    packagePath: "animated/BrushedTitaniumButton.tsx",
    files: ["animated/BrushedTitaniumButton.tsx"],
    propDefs: [
      { name: "children", type: "string", default: "Titanium Button", description: "Button text label", required: false },
      { name: "disabled", type: "boolean", default: false, description: "Disable button state", required: false }
    ],
  },
  {
    name: "Liquid Gold Button",
    slug: "liquid-gold-button",
    category: "buttons",
    description: "Conic gradient rotating behind a frosted glass blur layer, with a 1px border that catches light only at the top.",
    dependencies: ["framer-motion"],
    packagePath: "animated/LiquidGoldButton.tsx",
    files: ["animated/LiquidGoldButton.tsx"],
    propDefs: [
      { name: "children", type: "string", default: "Liquid Gold", description: "Button text label", required: false }
    ],
  },
  {
    name: "Guilloche Button",
    slug: "guilloche-button",
    category: "buttons",
    description: "Watch dial Guilloché patterns generating Moire wave shapes under the cursor spotlight.",
    dependencies: ["framer-motion"],
    packagePath: "animated/GuillocheButton.tsx",
    files: ["animated/GuillocheButton.tsx"],
    propDefs: [
      { name: "children", type: "string", default: "Guilloché", description: "Button text label", required: false }
    ],
  },
  {
    name: "Button Alpha",
    slug: "button-alpha",
    category: "buttons",
    description: "High-friction matte polymer button with fine light-catching bevel borders and heavy Z-axis mechanical compression.",
    dependencies: ["framer-motion"],
    packagePath: "animated/ButtonAlpha.tsx",
    files: ["animated/ButtonAlpha.tsx"],
    propDefs: [
      { name: "children", type: "string", default: "ACTIVATE", description: "Button text label", required: false },
      { name: "shape", type: "select", default: "pill", description: "Button border shape", required: false, options: ["pill", "full", "square"] },
      { name: "theme", type: "select", default: "charcoal", description: "Color theme variation", required: false, options: ["charcoal", "danger", "tactical"] }
    ],
  },
  {
    name: "Animated Beam",
    slug: "animated-beam",
    category: "animated",
    description: "An animated, coordinate-tracking connection beam connecting premium recessed beveled nodes in a modular hub-integration grid.",
    dependencies: ["framer-motion"],
    packagePath: "animated/animated-beam/BeveledBeamShowcase.tsx",
    files: [
      "animated/animated-beam/index.ts",
      "animated/animated-beam/AnimatedBeam.tsx",
      "animated/animated-beam/BeveledNode.tsx",
      "animated/animated-beam/BeveledBeamShowcase.tsx",
    ],
    propDefs: [
      { name: "variant", type: "select", default: "default", description: "Color theme variation", required: false, options: ["default", "monochrome", "neon"] },
      { name: "pathWidth", type: "number", default: 1.5, description: "Stroke width of the path line", required: false, min: 0.5, max: 8, step: 0.5 },
      { name: "pathOpacity", type: "number", default: 0.5, description: "Stroke opacity of static background line", required: false, min: 0.1, max: 1, step: 0.05 },
      { name: "duration", type: "number", default: 3.5, description: "Duration in seconds of gradient travel sweep", required: false, min: 1, max: 10, step: 0.5 }
    ],
  },
  {
    name: "Pixel Melt",
    slug: "pixel-melt",
    category: "backgrounds",
    description: "A full-viewport pixel grid that glows and cools under cursor heat, leaving behind a slow melt trail.",
    dependencies: [],
    packagePath: "backgrounds/PixelMelt.tsx",
    files: ["backgrounds/PixelMelt.tsx"],
    presentationStrategy: "fullscreen",
  },
  {
    name: "Breathing Grid",
    slug: "breathing-grid",
    category: "backgrounds",
    description: "An orthogonal grid with a slow left-to-right traveling wave, with local brightness boost near the cursor.",
    dependencies: [],
    packagePath: "backgrounds/BreathingGrid.tsx",
    files: ["backgrounds/BreathingGrid.tsx"],
    presentationStrategy: "fullscreen",
  },
  {
    name: "Floating Embers",
    slug: "floating-embers",
    category: "backgrounds",
    description: "Glowing ember particles that float upward with a gentle sway, reacting subtly to cursor and scroll.",
    dependencies: [],
    packagePath: "backgrounds/FloatingEmbers.tsx",
    files: ["backgrounds/FloatingEmbers.tsx"],
    presentationStrategy: "fullscreen",
  },
  {
    name: "Spotlight Grid",
    slug: "spotlight-grid",
    category: "backgrounds",
    description: "A dark grid with decorative tech icons and a dual-layer mouse-following spotlight effect using screen and color-dodge blend modes.",
    dependencies: [],
    packagePath: "backgrounds/SpotlightGrid.tsx",
    files: ["backgrounds/SpotlightGrid.tsx"],
    presentationStrategy: "fullscreen",
  },
  {
    name: "Lumina Wave",
    slug: "lumina-wave",
    category: "backgrounds",
    description: "An atmospheric WebGL background rendering undulating wave patterns resembling an aurora, featuring interactive mouse-bending and color personalization.",
    dependencies: [],
    packagePath: "backgrounds/LuminaWave.tsx",
    files: ["backgrounds/LuminaWave.tsx"],
    presentationStrategy: "fullscreen",
  },
  {
    name: "Matrix Rain",
    slug: "matrix-rain",
    category: "backgrounds",
    description: "A canvas-driven digital rain simulation displaying streaming glowing characters and icons in a premium monochrome aesthetic.",
    dependencies: [],
    packagePath: "backgrounds/MatrixRain.tsx",
    files: ["backgrounds/MatrixRain.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "speed", type: "number", default: 1.0, description: "Falling speed multiplier", required: false, min: 0.2, max: 4, step: 0.1 },
      { name: "density", type: "number", default: 1.0, description: "Stream column density factor", required: false, min: 0.2, max: 3, step: 0.1 },
      { name: "fontSize", type: "number", default: 16, description: "Size of characters in pixels", required: false, min: 10, max: 36, step: 2 },
      { name: "decayRate", type: "number", default: 0.05, description: "Trail fade overlay speed", required: false, min: 0.01, max: 0.2, step: 0.01 },
      { name: "glowStrength", type: "number", default: 8, description: "Neon blur glow radius of stream head", required: false, min: 0, max: 20, step: 2 },
      { name: "opacity", type: "number", default: 0.35, description: "Canvas transparency opacity", required: false, min: 0.1, max: 1.0, step: 0.05 },
      { name: "color", type: "color", default: "#525252", description: "Color of trailing code segments", required: false },
      { name: "glowColor", type: "color", default: "#ffffff", description: "Color of leading glowing header symbol", required: false }
    ],
  },


  {
    name: "Metallic Form",
    slug: "metallic-form",
    category: "animated",
    description: "A machined-metal obsidian form container with sequential entry animations, validation overlays, and typing state signals.",
    dependencies: ["framer-motion"],
    packagePath: "animated/MetallicForm.tsx",
    files: ["animated/MetallicForm.tsx"],
  },
  {
    name: "Pookie Form",
    slug: "pookie-form",
    category: "animated",
    description: "An industrial-grade registration plate form component inspired by Braun, Muji, and Dieter Rams. Features corner screws, deep inset inputs, and heavy tactile buttons.",
    dependencies: ["framer-motion"],
    packagePath: "animated/PookieForm.tsx",
    files: ["animated/PookieForm.tsx"],
    propDefs: [
      { name: "title", type: "string", default: "Workshop Entry", description: "Main plate header title", required: false },
      { name: "serialNumber", type: "string", default: "REGISTER / SERIAL NO. 04-2024", description: "Top serial code", required: false },
      { name: "buttonText", type: "string", default: "SUBMIT PLATE", description: "Button text label", required: false },
      { name: "backgroundColor", type: "color", default: "#ECE9DF", description: "Hex background color", required: false },
      { name: "paperTexture", type: "boolean", default: true, description: "Subtle recycled paper fiber grid texture overlay", required: false },
      { name: "showScrews", type: "boolean", default: true, description: "Show corner brushed aluminum workshop screws", required: false },
      { name: "shadowIntensity", type: "select", default: "medium", description: "Card elevation shadow depth style", required: false, options: ["low", "medium", "high"] },
      { name: "rounded", type: "select", default: "lg", description: "Corner radius style", required: false, options: ["sm", "md", "lg", "xl", "none"] },
    ],
  },
  {
    name: "Anisotropic Knob",
    slug: "anisotropic-knob",
    category: "primitives",
    description: "Machined metal rotary dial knob component with dynamic rotating anisotropic highlights, snapper increments, and accessibility controls.",
    dependencies: ["framer-motion"],
    packagePath: "animated/AnisotropicKnob.tsx",
    files: ["animated/AnisotropicKnob.tsx"],
    propDefs: [
      { name: "variant", type: "select", default: "slider", description: "Knob behavior mode", required: false, options: ["slider", "infinite"] },
      { name: "min", type: "number", default: 0, description: "Minimum slider value", required: false, min: -100, max: 100, step: 10 },
      { name: "max", type: "number", default: 100, description: "Maximum slider value", required: false, min: 10, max: 500, step: 10 },
      { name: "step", type: "number", default: 1, description: "Snap increments", required: false, min: 1, max: 50, step: 1 },
      { name: "size", type: "number", default: 112, description: "Diameter of the knob in pixels", required: false, min: 80, max: 200, step: 10 },
      { name: "label", type: "string", default: "VOLUME", description: "Label text", required: false },
      { name: "sound", type: "boolean", default: true, description: "Enable click feedback sound", required: false },
    ],
  },
  {
    name: "Mechanical Timer",
    slug: "mechanical-timer",
    category: "widgets",
    description: "Machined metal tactile timer/stopwatch component with dragging physical dials, mechanical cogwheel meshes, Web Audio click synthesis ticks, and glowing segment MM:SS.CC timer displays.",
    dependencies: ["framer-motion", "lucide-react"],
    packagePath: "animated/MechanicalTimer.tsx",
    files: ["animated/MechanicalTimer.tsx"],
    propDefs: [
      { name: "rimColor", type: "color", default: "#a78bfa", description: "Color of the active LED progress ring", required: false },
      { name: "defaultDuration", type: "number", default: 30, description: "Default starting duration in seconds", required: false, min: 5, max: 60, step: 5 },
    ],
  },
  {
    name: "Laser Vault Password",
    slug: "laser-vault-password",
    category: "widgets",
    description: "Passcode vault keypad with laser-etch cooling characters, dynamic cursor sweeps, tactile clicks, container rattles, and friction-metal creak alarms.",
    dependencies: ["framer-motion", "lucide-react"],
    packagePath: "animated/LaserVaultPassword.tsx",
    files: ["animated/LaserVaultPassword.tsx"],
  },
  {
    name: "Premium Hero",
    slug: "premium-hero",
    category: "animated",
    description: "Interactive Hero Section featuring floating 3D cards, typewriter search, spring CTA, and paper-notebook grid aesthetics.",
    dependencies: ["framer-motion", "lucide-react"],
    packagePath: "animated/PremiumHero.tsx",
    files: ["animated/PremiumHero.tsx"],
    presentationStrategy: "cover",
  },
  {
    name: "Dot Matrix",
    slug: "dot-matrix",
    category: "animated",
    description: "Highly optimized, programmable LED dot matrix display supporting Perlin noise, typewriter bitmaps, Web Audio integration, interactive cursor repelling, and custom plugin architectures.",
    dependencies: ["framer-motion"],
    packagePath: "animated/DotMatrix.tsx",
    files: [
      "matrix/DotMatrix.tsx",
      "matrix/Dot.tsx",
      "matrix/types.ts",
      "matrix/animations/plugins.ts",
      "matrix/animations/index.ts",
      "matrix/hooks/useMouseInfluence.ts",
      "matrix/hooks/useRAF.ts",
      "matrix/utils/distance.ts",
      "matrix/utils/noise.ts",
      "matrix/utils/bitmap.ts",
    ],
    propDefs: [
      { name: "animation", type: "select", default: "scroll-text", description: "Animation mode", required: false, options: ["wave", "text", "scroll-text", "clock", "equalizer", "noise", "sparkle", "ripple", "snake", "rain"] },
      { name: "text", type: "string", default: "VOID UI", description: "Text content (for text/scroll-text modes)", required: false },
      { name: "columns", type: "number", default: 44, description: "Number of dot columns", required: false, min: 10, max: 80, step: 1 },
      { name: "rows", type: "number", default: 12, description: "Number of dot rows", required: false, min: 4, max: 24, step: 1 },
      { name: "color", type: "color", default: "#e7e5df", description: "Active dot color", required: false },
      { name: "speed", type: "number", default: 1, description: "Animation speed multiplier", required: false, min: 0.1, max: 5, step: 0.1 },
      { name: "glow", type: "boolean", default: true, description: "Enable glow effect on dots", required: false },
    ],
  },
  {
    name: "Scroll Progress",
    slug: "scroll-progress",
    category: "animated",
    description: "A vertical dynamic scrollbar overlay with interactive tick mark animations, dragging controls, and velocity-based stretching/glow.",
    dependencies: ["framer-motion"],
    packagePath: "animated/scrollprogress/ScrollProgress.tsx",
    files: [
      "animated/scrollprogress/ScrollProgress.tsx",
      "animated/scrollprogress/Tick.tsx",
      "animated/scrollprogress/useScrollProgress.ts",
      "animated/scrollprogress/types.ts",
      "animated/scrollprogress/utils.ts",
    ],
    propDefs: [
      { name: "ticks", type: "number", default: 42, description: "Number of vertical tick marks", required: false, min: 10, max: 100, step: 1 },
      { name: "color", type: "color", default: "#a855f7", description: "Color of the active scroll indicator", required: false },
      { name: "glow", type: "boolean", default: true, description: "Enable glow halo around the active indicator", required: false },
      { name: "height", type: "number", default: 44, description: "Thickness (width) of the scrollbar in pixels", required: false, min: 20, max: 100, step: 2 },
      { name: "width", type: "number", default: 320, description: "Length (height) of the scrollbar in pixels", required: false, min: 150, max: 600, step: 10 },
      { name: "variant", type: "select", default: "default", description: "Design variant of the scroll-bar", required: false, options: ["default", "prominent", "inverted"] },
    ],
  },
  {
    name: "Scroll Path Draw",
    slug: "scroll-path-draw",
    category: "animated",
    description: "An animated scroll-linked SVG path drawer supporting scroll-jacked viewport locks and passive viewport animations with multiple visual variants.",
    dependencies: ["framer-motion"],
    packagePath: "animated/scrollpath/ScrollPathContainer.tsx",
    files: [
      "animated/scrollpath/ScrollPathContext.tsx",
      "animated/scrollpath/ScrollPathContainer.tsx",
      "animated/scrollpath/variants/ScrollPathWaves.tsx",
      "animated/scrollpath/variants/ScrollPathCircuit.tsx",
      "animated/scrollpath/variants/ScrollPathProcess.tsx",
      "animated/scrollpath/index.ts",
    ],
    propDefs: [
      { name: "mode", type: "select", default: "scroll-jack", description: "Scroll tracking mode", required: false, options: ["scroll-jack", "passive"] },
      { name: "sensitivity", type: "number", default: 1, description: "Sensitivity factor for scroll-jacking", required: false, min: 0.1, max: 5, step: 0.1 },
    ],
  },
  {
    name: "Now Playing Card",
    slug: "now-playing-card",
    category: "animated",
    description: "A Spotify-style vinyl player card powered by Last.fm API that dynamically retrieves real-time listening history with vinyl spin animations.",
    dependencies: ["react-icons"],
    packagePath: "animated/NowPlayingCard.tsx",
    files: ["animated/NowPlayingCard.tsx"],
  },
  {
    name: "Wheel Picker",
    slug: "wheel-picker",
    category: "animated",
    description: "Premium physical-feeling 3D wheel picker with momentum dragging, spring snapping, and mechanical Web Audio crown clicks.",
    dependencies: ["framer-motion"],
    packagePath: "animated/WheelPicker.tsx",
    files: [
      "animated/WheelPicker.tsx",
      "animated/react-wheel-picker/index.ts",
      "animated/react-wheel-picker/types.ts",
      "animated/react-wheel-picker/components/WheelPicker.tsx",
      "animated/react-wheel-picker/components/Cylinder.tsx",
      "animated/react-wheel-picker/components/WheelItem.tsx",
      "animated/react-wheel-picker/components/SelectionOverlay.tsx",
      "animated/react-wheel-picker/hooks/useCylinderTransform.ts",
      "animated/react-wheel-picker/hooks/useInfiniteLoop.ts",
      "animated/react-wheel-picker/hooks/useAudio.ts",
      "animated/react-wheel-picker/hooks/useWheel.ts",
      "animated/react-wheel-picker/hooks/useMomentum.ts",
      "animated/react-wheel-picker/hooks/useSnap.ts",
      "animated/react-wheel-picker/utils/physics.ts",
      "animated/react-wheel-picker/utils/audio.ts",
      "animated/react-wheel-picker/utils/math.ts",
    ],
    propDefs: [
      { name: "variant", type: "select", default: "glass", description: "Visual style of the picker", required: false, options: ["glass", "minimal", "void"] },
      { name: "loop", type: "boolean", default: false, description: "Allow infinite looping through items", required: false },
      { name: "sound", type: "boolean", default: true, description: "Play mechanical click sound on selection change", required: false },
      { name: "disabled", type: "boolean", default: false, description: "Disable interaction and pointer events", required: false },
      { name: "itemHeight", type: "number", default: 40, description: "Height of each item in pixels", required: false, min: 20, max: 100, step: 1 },
      { name: "visibleItems", type: "number", default: 5, description: "Number of visible items in the viewport", required: false, min: 3, max: 11, step: 1 },
      { name: "perspective", type: "number", default: 1000, description: "3D perspective depth in pixels", required: false, min: 200, max: 2000, step: 50 },
    ],
  },
  {
    name: "Weapon Wheel",
    slug: "weapon-wheel",
    category: "animated",
    description: "Premium GTA V-inspired selection wheel designed for development tools, featuring interactive SVG slices, Tabler icons, mechanical clicks, and live stats dashboards.",
    dependencies: ["framer-motion", "@tabler/icons-react"],
    packagePath: "animated/WeaponWheel.tsx",
    files: ["animated/WeaponWheel.tsx"],
    propDefs: [
      { name: "variant", type: "select", default: "default", description: "Visual style of the dashboard canvas", required: false, options: ["default", "wheel-3", "wheel-4"] },
      { name: "inline", type: "boolean", default: true, description: "Whether to render inline in the page canvas instead of a full-screen popup modal overlay", required: false },
      { name: "triggerKey", type: "string", default: "q", description: "Keyboard key to hold to trigger the selection overlay in modal mode", required: false },
    ],
  },
  {
    name: "Names Landing",
    slug: "names-landing",
    category: "animated",
    description: "Premium interactive names hero canvas with organic constellation, grid, and helical layouts, search filtering, and parallax depth layers.",
    dependencies: ["framer-motion"],
    packagePath: "animated/NamesLanding/NamesLanding.tsx",
    files: [
      "animated/NamesLanding/NamesLanding.tsx",
      "animated/NamesLanding/NameItem.tsx",
      "animated/NamesLanding/BackgroundLayer.tsx",
      "animated/NamesLanding/layoutEngine.ts"
    ],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "variant", type: "select", default: "constellation", description: "Procedural layout style", required: false, options: ["constellation", "grid", "helical"] },
      { name: "background", type: "select", default: "solid", description: "Canvas background theme style", required: false, options: ["solid", "noise", "paper", "grid", "gradient", "texture"] },
      { name: "fontFamily", type: "select", default: "sans", description: "Primary font family styling", required: false, options: ["sans", "mono", "grotesk", "serif", "suisse"] },
      { name: "fontScale", type: "number", default: 1.0, description: "Font size scaling factor", required: false, min: 0.5, max: 2.5, step: 0.1 },
      { name: "spacing", type: "number", default: 1.0, description: "Spacing separation scale", required: false, min: 0.5, max: 2.5, step: 0.1 },
      { name: "density", type: "number", default: 2, description: "Layout density levels (1: sparse, 2: balanced, 3: dense)", required: false, min: 1, max: 3, step: 1 },
      { name: "showSearch", type: "boolean", default: true, description: "Render top filter catalogue input overlay", required: false },
      { name: "colorMode", type: "select", default: "dark", description: "Color theme mode", required: false, options: ["light", "dark"] },
      { name: "title", type: "string", default: "CATALOGUE", description: "Exhibition large backdrop title text", required: false },
      { name: "subtitle", type: "string", default: "SPATIAL TYPOGRAPHY EXHIBIT / VOID UI", description: "Sub-label background metadata description", required: false },
    ]
  },
  {
    name: "Hero Landing",
    slug: "hero",
    category: "animated",
    description: "Highly configurable, responsive portfolio hero landing page with technical grids and interactive pixel art decorations.",
    dependencies: ["framer-motion"],
    packagePath: "animated/Hero.tsx",
    files: ["animated/Hero.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "name", type: "string", default: "stephanie", description: "Giant display wordmark name text", required: true },
      { name: "bgColor", type: "color", default: "#1E3FEB", description: "Saturated canvas background color", required: false },
      { name: "gridOpacity", type: "number", default: 0.06, description: "Line opacity of repeating background grids", required: false, min: 0.0, max: 0.3, step: 0.01 },
      { name: "fontFamily", type: "select", default: "instrument", description: "Primary serif display typeface", required: false, options: ["instrument", "fraunces", "playfair", "newsreader", "custom"] },
      { name: "monoFontFamily", type: "select", default: "dotgothic", description: "Monospace labels/nav typeface", required: false, options: ["dotgothic", "silkscreen", "pressstart", "vt323", "pixelify", "jersey"] },
      { name: "iconVariant", type: "select", default: "flower", description: "Pixel art decoration icon shape", required: false, options: ["flower", "heart", "star", "skull", "crown", "ghost", "none"] },
      { name: "iconAnimation", type: "select", default: "static", description: "Interactive animation variant behavior", required: false, options: ["static", "hover-bloom", "idle-loop", "scroll-linked", "clickable"] },
      { name: "iconPosition", type: "select", default: "inline", description: "Visual alignment relative to wordmark name text", required: false, options: ["inline", "top-right", "bottom-right", "top-left", "bottom-left"] },
      { name: "iconSize", type: "number", default: 36, description: "Size dimensions of the central pixel icon", required: false, min: 16, max: 80, step: 4 },
      { name: "iconRotation", type: "number", default: 0, description: "Initial rotation tilt angle in degrees", required: false, min: -360, max: 360, step: 15 },
      { name: "introduction", type: "string", default: "I build high-end interactive visual systems and graphics for digital exhibitions, museums, and products.", description: "Sub-headline description paragraph below name", required: false },
      { name: "pixelDensity", type: "select", default: "medium", description: "Count of floating pixel crosses on canvas", required: false, options: ["sparse", "medium", "dense"] },
      { name: "enableParallax", type: "boolean", default: true, description: "Mouse cursor follow spring parallax effect", required: false },
      { name: "animationSpeed", type: "select", default: "normal", description: "Crosses floating speed multiplier", required: false, options: ["slow", "normal", "fast"] },
      { name: "backgroundIconVariant", type: "select", default: "cross", description: "Pixel art icon shape used uniformly across background floating layout", required: false, options: ["flower", "heart", "star", "skull", "crown", "ghost", "cross"] },
      { name: "backgroundIconCount", type: "number", default: 8, description: "Total count of background floating icons to scatter", required: false, min: 2, max: 24, step: 1 },
    ]
  },
  {
    name: "Expand On Hover",
    slug: "expand-on-hover",
    category: "animated",
    description: "A stack of compact preview cards that smoothly expand into immersive content panels on hover, featuring physical parting animations and 3D pointer tracking.",
    dependencies: ["framer-motion"],
    packagePath: "animated/expand-on-hover/components/expand-on-hover/ExpandOnHover.tsx",
    files: [
      "animated/expand-on-hover/index.ts",
      "animated/expand-on-hover/types.ts",
      "animated/expand-on-hover/hooks/useExpand.ts",
      "animated/expand-on-hover/components/expand-on-hover/ExpandOnHover.tsx",
      "animated/expand-on-hover/components/expand-on-hover/Preview.tsx",
      "animated/expand-on-hover/components/expand-on-hover/CardContent.tsx",
      "animated/expand-on-hover/components/expand-on-hover/ExpandCard.tsx",
    ],
  },
  {
    name: "Text Shuffle",
    slug: "text-shuffle",
    category: "animated",
    description: "A text animation component that shuffles characters with multiple variants including cipher, scramble, and typewriter effects.",
    dependencies: ["framer-motion"],
    packagePath: "animated/text-shuffle/TextShuffle.tsx",
    files: [
      "animated/text-shuffle/index.ts",
      "animated/text-shuffle/TextShuffle.tsx",
      "animated/text-shuffle/AnimatedWord.tsx",
      "animated/text-shuffle/types.ts",
      "animated/text-shuffle/hooks/useShuffleVariants.ts",
      "animated/text-shuffle/hooks/useShuffleCycle.ts",
      "animated/text-shuffle/utils/splitCharacters.ts",
      "animated/text-shuffle/utils/timing.ts",
    ],
    propDefs: [
      { name: "variant", type: "select", default: "blurReveal", description: "Visual morph variant", required: false, options: ["scramble", "wave", "glitch", "elastic", "flipIn", "blurReveal"] },
      { name: "duration", type: "number", default: 2200, description: "Display duration per word (ms)", required: false, min: 500, max: 8000, step: 100 },
      { name: "transition", type: "number", default: 700, description: "Transition duration between words (ms)", required: false, min: 100, max: 2000, step: 50 },
      { name: "loop", type: "boolean", default: true, description: "Loop cycling infinitely", required: false },
      { name: "pauseOnHover", type: "boolean", default: false, description: "Pause on hover", required: false },
      { name: "cursorBlink", type: "boolean", default: false, description: "Show blinking cursor", required: false },
      { name: "uppercase", type: "boolean", default: false, description: "Force uppercase", required: false },
      { name: "outline", type: "boolean", default: false, description: "Render text as outline stroke", required: false },
      { name: "fontSize", type: "string", default: "clamp(2.5rem,8vw,6rem)", description: "Font size CSS value", required: false },
    ],
  },
  {
    name: "Cards",
    slug: "cards",
    category: "animated",
    description: "A fanned deck of dark editorial cards with B&W images, prismatic top-border highlights, spring-physics animations, and an expand-on-click description reveal.",
    dependencies: ["framer-motion"],
    packagePath: "animated/Cards.tsx",
    files: ["animated/Cards.tsx"],
    presentationStrategy: "center",
  },
  {
    name: "Simple Card",
    slug: "simple-card",
    category: "animated",
    description: "A single dark editorial card with a padded B&W image, prismatic top-border highlight, Instrument Serif title pinned to the bottom, and an expand-on-click description reveal.",
    dependencies: ["framer-motion"],
    packagePath: "animated/SimpleCard.tsx",
    files: ["animated/SimpleCard.tsx"],
    presentationStrategy: "center",
  },
  {
    name: "Flickering Grid Playground",
    slug: "flickering-grid-playground",
    category: "animated",
    description: "An interactive cockpit controller playground for experimenting with grid sizing, gaps, flicker chance, and curated presets.",
    dependencies: [],
    packagePath: "animated/FlickeringGridPlayground.tsx",
    files: ["animated/FlickeringGridPlayground.tsx"],
    presentationStrategy: "fullscreen",
  },
  {
    name: "Dot Pattern Playground",
    slug: "dot-pattern-playground",
    category: "animated",
    description: "An interactive cockpit controller playground for dynamic dot sizes, gaps, custom swatches, and interactive spotlight masking.",
    dependencies: [],
    packagePath: "animated/DotPatternPlayground.tsx",
    files: ["animated/DotPatternPlayground.tsx"],
    presentationStrategy: "fullscreen",
  },
  {
    name: "Cards Two (3D Orbit Ring)",
    slug: "cards-two",
    category: "animated",
    description: "A premium spatial 3D circular card carousel that arranges cards around an invisible 3D ring with momentum dragging, snapping, reflection, lighting depth, and custom transforms.",
    dependencies: ["framer-motion"],
    packagePath: "animated/CardsTwo/CardsTwo.tsx",
    files: [
      "animated/CardsTwo/CardsTwo.tsx",
      "animated/CardsTwo/types.ts",
      "animated/CardsTwo/hooks/useCylinder.ts",
      "animated/CardsTwo/hooks/useRotation.ts",
      "animated/CardsTwo/hooks/useCardTransforms.ts",
      "animated/CardsTwo/hooks/useCardsTwo.ts"
    ],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "radius", type: "number", default: 500, description: "Cylinder radius in pixels", required: false, min: 200, max: 1000, step: 20 },
      { name: "gap", type: "number", default: 40, description: "Spacing between cards in pixels", required: false, min: 0, max: 150, step: 5 },
      { name: "cardWidth", type: "number", default: 300, description: "Card width in pixels", required: false, min: 150, max: 450, step: 10 },
      { name: "cardHeight", type: "number", default: 400, description: "Card height in pixels", required: false, min: 200, max: 550, step: 10 },
      { name: "rotationAxis", type: "select", default: "y", description: "Cylinder rotation axis", required: false, options: ["x", "y", "z"] },
      { name: "rotationDirection", type: "select", default: "clockwise", description: "Auto-rotation direction", required: false, options: ["clockwise", "counter-clockwise"] },
      { name: "rotationSpeed", type: "number", default: 36, description: "Auto-rotation speed (deg/sec)", required: false, min: 0, max: 120, step: 1 },
      { name: "autoRotate", type: "boolean", default: true, description: "Enable auto-rotation", required: false },
      { name: "draggable", type: "boolean", default: true, description: "Enable mouse/touch dragging", required: false },
      { name: "scrollRotate", type: "boolean", default: false, description: "Enable mouse wheel scroll rotation", required: false },
      { name: "snap", type: "boolean", default: true, description: "Snap to nearest card when released", required: false },
      { name: "perspective", type: "number", default: 1200, description: "3D Perspective depth", required: false, min: 400, max: 2500, step: 100 },
      { name: "depth", type: "number", default: 0, description: "Cylinder depth offset (Z)", required: false, min: -400, max: 400, step: 10 },
      { name: "visibleArc", type: "number", default: 360, description: "Visible arc spread in degrees", required: false, min: 60, max: 360, step: 10 },
      { name: "cameraDistance", type: "number", default: 0, description: "Camera Z position offset", required: false, min: -800, max: 800, step: 50 },
      { name: "activeScale", type: "number", default: 1.1, description: "Scale of centered active card", required: false, min: 0.8, max: 1.8, step: 0.05 },
      { name: "activeOpacity", type: "number", default: 1.0, description: "Opacity of centered active card", required: false, min: 0.2, max: 1.0, step: 0.05 },
      { name: "activeBrightness", type: "number", default: 1.0, description: "Brightness spotlight of active card", required: false, min: 0.3, max: 2.0, step: 0.05 },
      { name: "sideScale", type: "number", default: 0.8, description: "Scale of side/distant cards", required: false, min: 0.4, max: 1.4, step: 0.05 },
      { name: "sideOpacity", type: "number", default: 0.6, description: "Opacity of side/distant cards", required: false, min: 0.1, max: 1.0, step: 0.05 },
      { name: "sideBrightness", type: "number", default: 0.7, description: "Brightness of side/distant cards", required: false, min: 0.1, max: 1.5, step: 0.05 },
      { name: "backScale", type: "number", default: 0.6, description: "Scale of back/furthest cards", required: false, min: 0.2, max: 1.4, step: 0.05 },
      { name: "backOpacity", type: "number", default: 0.0, description: "Opacity of cards in back half", required: false, min: 0.0, max: 1.0, step: 0.05 },
      { name: "backBrightness", type: "number", default: 0.4, description: "Brightness of back/furthest cards", required: false, min: 0.0, max: 1.5, step: 0.05 },
      { name: "hideBackCards", type: "boolean", default: true, description: "Hide cards in the back entirely", required: false },
      { name: "shadowIntensity", type: "number", default: 0.5, description: "Shadow black opacity underneath", required: false, min: 0.0, max: 1.0, step: 0.05 },
      { name: "depthBlur", type: "boolean", default: true, description: "Blur background cards based on distance", required: false },
      { name: "blurStrength", type: "number", default: 4, description: "Strength of blur on far cards", required: false, min: 0, max: 24, step: 1 },
      { name: "reflection", type: "boolean", default: false, description: "Display mirror reflection under cards", required: false },
      { name: "ringTiltX", type: "number", default: 15, description: "Cylinder ring X tilt (isometric pitch)", required: false, min: -45, max: 45, step: 1 },
      { name: "ringTiltY", type: "number", default: 0, description: "Cylinder ring Y tilt (isometric yaw)", required: false, min: -45, max: 45, step: 1 },
      { name: "faceCamera", type: "boolean", default: false, description: "Force cards to face camera flatly", required: false },
      { name: "tiltX", type: "number", default: 0, description: "Constant pitch tilt (deg)", required: false, min: -30, max: 30, step: 1 },
      { name: "tiltY", type: "number", default: 0, description: "Constant yaw tilt (deg)", required: false, min: -30, max: 30, step: 1 },
      { name: "tiltZ", type: "number", default: 0, description: "Constant roll tilt (deg)", required: false, min: -30, max: 30, step: 1 },
    ],
  },
  {
    name: "Animated Icons 1",
    slug: "animated-icons-1",
    category: "animated",
    description: "Nine Tabler icons in small monochrome black cards. Click any card to fire its unique animation — triple spin, nuclear collapse, hex facet snap, supernova burst, lemniscate shudder, glitch disintegrate, lightning strike, helix flip, or vortex implosion. Pure monochrome, no color, no shadows.",
    dependencies: ["framer-motion", "@tabler/icons-react"],
    packagePath: "animated/Loaders1.tsx",
    files: ["animated/Loaders1.tsx", "animated/LoaderCard.tsx"],
    presentationStrategy: "fullscreen",
  },
  {
    name: "Dashed Feature Card",
    slug: "dashed-feature-card",
    category: "animated",
    description: "A dark-themed editorial feature card with interactive L-shaped crop corner overlays, dashed inner icon frames, and spring-physics animations.",
    dependencies: ["framer-motion", "@tabler/icons-react"],
    packagePath: "animated/DashedFeatureCard.tsx",
    files: ["animated/DashedFeatureCard.tsx"],
    propDefs: [
      { name: "title", type: "string", default: "My Issues", description: "The primary bold title text", required: true },
      { name: "description", type: "string", default: "Issue tracker", description: "The secondary muted subtitle text", required: true },
      { name: "borderStyle", type: "select", default: "dashed", description: "The style of the border line", options: ["dashed", "dotted", "solid"], required: false },
      { name: "rounded", type: "select", default: "none", description: "Border radius of the card container", options: ["none", "sm", "md", "lg", "xl", "2xl"], required: false },
      { name: "iconRounded", type: "select", default: "none", description: "Border radius of the icon wrapper", options: ["none", "sm", "md", "lg", "xl", "2xl"], required: false },
      { name: "dashLength", type: "number", default: 8, description: "Length of each dash in pixels", required: false, min: 1, max: 30, step: 1 },
      { name: "dashGap", type: "number", default: 4, description: "Spacing gap between dashes/dots", required: false, min: 1, max: 30, step: 1 },
      { name: "dashWidth", type: "number", default: 1, description: "Stroke thickness of dashed border line", required: false, min: 1, max: 10, step: 1 },
      { name: "dashColor", type: "string", default: "rgba(255, 255, 255, 0.22)", description: "Color string of dashes", required: false },
      { name: "dashHoverColor", type: "string", default: "rgba(255, 255, 255, 0.55)", description: "Color string of dashes on hover", required: false },
      { name: "dashOpacity", type: "number", default: 1.0, description: "Normal dash opacity", required: false, min: 0.0, max: 1.0, step: 0.1 },
      { name: "dashHoverOpacity", type: "number", default: 1.0, description: "Hover dash opacity", required: false, min: 0.0, max: 1.0, step: 0.1 },
      { name: "dashShift", type: "number", default: 8, description: "Shift offset magnitude in pixels on hover", required: false, min: 0, max: 30, step: 1 },
      { name: "showCorners", type: "boolean", default: true, description: "Render corner crop marks", required: false },
      { name: "cornerColor", type: "string", default: "#525252", description: "Color of crop line corners", required: false },
      { name: "cornerHoverColor", type: "string", default: "#f5f5f5", description: "Hover color of crop line corners", required: false },
      { name: "cornerLength", type: "number", default: 14, description: "Leg length of crop corners in pixels", required: false, min: 4, max: 40, step: 1 },
      { name: "cornerWidth", type: "number", default: 2, description: "Line thickness of crop corners", required: false, min: 1, max: 8, step: 1 },
      { name: "cornerOffset", type: "number", default: 3, description: "Expand offset distance on hover", required: false, min: 0, max: 20, step: 1 },
      { name: "showShadow", type: "boolean", default: true, description: "Render card shadow", required: false },
      { name: "hoverScale", type: "number", default: 1.015, description: "Hover scale ratio", required: false, min: 0.95, max: 1.2, step: 0.005 },
      { name: "hoverY", type: "number", default: -4, description: "Hover lift distance in pixels", required: false, min: -20, max: 20, step: 1 },
    ],
  },
  {
    name: "Dashed Marquee",
    slug: "dashed-marquee",
    category: "animated",
    description: "An infinite scrolling marquee section utilizing custom edit-dashed cards and compact icon tiles with speed, direction, and corner blur settings.",
    dependencies: ["framer-motion", "@tabler/icons-react"],
    packagePath: "animated/DashedMarquee.tsx",
    files: ["animated/DashedMarquee.tsx", "animated/DashedFeatureCard.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "variant", type: "select", default: "default", description: "Display variant style", options: ["default", "icon"], required: false },
      { name: "cardVariant", type: "select", default: "dashed", description: "Design style of marquee cards", options: ["dashed", "bevel"], required: false },
      { name: "direction", type: "select", default: "right-to-left", description: "Movement direction of the track", options: ["left-to-right", "right-to-left", "up-to-down", "down-to-up"], required: false },
      { name: "speed", type: "number", default: 25, description: "Full loop animation duration in seconds", required: false, min: 5, max: 120, step: 1 },
      { name: "blurCorners", type: "boolean", default: true, description: "Whether to render gradient blur fade on container ends", required: false },
      { name: "pauseOnHover", type: "boolean", default: true, description: "Pause marquee sliding on mouse hover", required: false },
    ],
  },
  {
    name: "Bevel Accordion",
    slug: "bevel-accordion",
    category: "animated",
    description: "A tactile 3D beveled accordion stack matching the Props Tweaker styles, featuring rotating chevrons, heights transition, and neon glows shadow overlays.",
    dependencies: ["framer-motion"],
    packagePath: "animated/BevelAccordion.tsx",
    files: ["animated/BevelAccordion.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "allowMultiple", type: "boolean", default: false, description: "Allow multiple panels open at once", required: false },
      { name: "glowColor", type: "select", default: "blue", description: "Neon glow colors", options: ["blue", "white", "none"], required: false },
    ],
  },
  {
    name: "Sticker Card",
    slug: "sticker-card",
    category: "animated",
    description: "An interactive card that scatters bouncy physics-based stickers all over the viewport on hover.",
    dependencies: ["framer-motion", "lucide-react"],
    packagePath: "animated/StickerCard.tsx",
    files: ["animated/StickerCard.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "numStickers", type: "number", default: 7, description: "Number of scattered stickers to render", required: false, min: 5, max: 10, step: 1 },
    ],
  },
  {
    name: "Datepicker",
    slug: "datepicker",
    category: "animated",
    description: "A skeuomorphic 3D beveled calendar date picker with synth mechanical click sound feedback.",
    dependencies: ["framer-motion", "@tabler/icons-react"],
    packagePath: "animated/Datepicker.tsx",
    files: ["animated/Datepicker.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "glowColor", type: "select", default: "none", description: "Neon glow color behind the datepicker", options: ["none", "blue", "white"], required: false },
    ],
  },
  {
    name: "NavBar1",
    slug: "navbar-1",
    category: "animated",
    description: "A floating horizontal navigation panel console with sliding tabs, active status glows, and search well.",
    dependencies: ["framer-motion", "@tabler/icons-react"],
    packagePath: "animated/NavBar1.tsx",
    files: ["animated/NavBar1.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "statusColor", type: "select", default: "emerald", description: "Analog LED status light color indicator", options: ["emerald", "cyan", "rose"], required: false },
    ],
  },
  {
    name: "Bevel Alert Dialog",
    slug: "bevel-alert-dialog",
    category: "animated",
    description: "A tactile 3D beveled alert dialog panel matching the machined console aesthetic, featuring physical drop shadows, recessed wells, action buttons, and status LED alerts.",
    dependencies: ["framer-motion"],
    packagePath: "animated/BevelAlertDialog.tsx",
    files: ["animated/BevelAlertDialog.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "variant", type: "select", default: "info", description: "Visual and LED alert state theme", options: ["info", "danger"], required: false },
      { name: "title", type: "string", default: "ALARM CONSOLE INITIALIZED", description: "Main headline text", required: false },
      { name: "description", type: "string", default: "The security deck has booted successfully. All perimeter sensor scans are active and operating within nominal parameters.", description: "Explanation detail text", required: false },
      { name: "confirmLabel", type: "string", default: "PROCEED", description: "Primary action button label", required: false },
      { name: "cancelLabel", type: "string", default: "DISMISS", description: "Secondary action button label", required: false }
    ],
  },
];
