export type ComponentCategory =
  | "animated"
  | "primitives"
  | "charts"
  | "widgets"
  | "buttons"
  | "backgrounds";

export type DisplayStrategy = "center" | "fullscreen" | "cover" | "fit" | "auto";

export interface PropDefinition {
  name: string;
  type: "string" | "number" | "boolean" | "select" | "color" | (string & {});
  default?: string | number | boolean;
  description: string;
  required: boolean;
  options?: string[];       // for "select" type
  min?: number;            // for "number" type
  max?: number;            // for "number" type
  step?: number;           // for "number" type
}

export interface ComponentVariant {
  name: string;
  props: Record<string, unknown>;
}

export interface RegistryEntry {
  name: string;
  slug: string;
  category: ComponentCategory;
  description: string;
  dependencies: string[];
  packagePath: string;       // path inside packages/ui/src (kept for backward compat)
  files: string[];           // all source files relative to packages/ui/src/ (shadcn registry)
  propDefs?: PropDefinition[]; // tweakable props for the Props Tweaker panel
  variants?: ComponentVariant[];
  presentationStrategy?: DisplayStrategy;
}

export const registry: RegistryEntry[] = [
  {
    name: "Infinite Scroll",
    slug: "infinite-scroll",
    category: "animated",
    description: "Seamless infinite fullscreen scroll with parallax image effects, powered by Lenis smooth scrolling and GSAP scrub animations.",
    dependencies: ["gsap", "lenis"],
    packagePath: "animated/InfiniteScroll.tsx",
    files: ["animated/InfiniteScroll.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "parallaxPercent", type: "number", default: 50, description: "Parallax vertical offset percentage", required: false, min: 0, max: 100, step: 5 },
      { name: "snapDuration", type: "number", default: 0.9, description: "Snap animation duration in seconds", required: false, min: 0.3, max: 2, step: 0.1 },
      { name: "showProgress", type: "boolean", default: true, description: "Show a minimal dot progress indicator at the bottom", required: false },
      { name: "showLabels", type: "boolean", default: true, description: "Show slide label and caption overlays", required: false },
      { name: "showScrollCue", type: "boolean", default: true, description: "Show a 'Scroll' hint on the first slide", required: false },
      { name: "overlayOpacity", type: "number", default: 0.55, description: "Dark overlay gradient opacity (0 to 1)", required: false, min: 0, max: 1, step: 0.05 },
    ],
  },
  {
    name: "Roughly",
    slug: "roughly",
    category: "animated",
    description: "Organic, hand-drawn vector annotations designed for high-friction digital typography. Wobbly underlines, pen circles, editorial strikethroughs, curly brackets, and tactile highlights.",
    dependencies: ["framer-motion", "roughjs", "rough-notation"],
    packagePath: "animated/Roughly.tsx",
    files: [
      "animated/Roughly.tsx",
      "animated/roughly/index.ts",
      "animated/roughly/RoughArrow.tsx",
      "animated/roughly/RoughBox.tsx",
      "animated/roughly/RoughBracket.tsx",
      "animated/roughly/RoughCircle.tsx",
      "animated/roughly/RoughCross.tsx",
      "animated/roughly/RoughHighlight.tsx",
      "animated/roughly/RoughStrike.tsx",
      "animated/roughly/RoughUnderline.tsx",
    ],
    propDefs: [
      { name: "children", type: "React.ReactNode", description: "Target typography or elements to annotate with hand-drawn vector sketches", required: false },
      { name: "type", type: "select", default: "underline", description: "Style of organic hand-drawn annotation sketch", required: false, options: ["underline", "box", "circle", "highlight", "strike-through", "crossed-off", "bracket"] },
      { name: "color", type: "color", default: "#e11d48", description: "Stroke or highlighter accent tint color", required: false },
      { name: "strokeWidth", type: "number", default: 2, min: 1, max: 8, step: 0.5, description: "Thickness of the rough vector sketch strokes in pixels", required: false },
      { name: "animate", type: "boolean", default: true, description: "Whether to animate the organic drawing stroke on mount", required: false },
      { name: "animationDuration", type: "number", default: 800, min: 200, max: 2000, step: 50, description: "Total duration of drawing stroke animation in milliseconds", required: false },
      { name: "brackets", type: "select", default: "left", description: "Placement side when type is set to 'bracket'", required: false, options: ["left", "right", "top", "bottom"] },
      { name: "className", type: "string", description: "Additional wrapper CSS class names", required: false },
    ],
  },
  {
    name: "Image Reveal",
    slug: "image-reveal",
    category: "animated",
    description: "Multi-layered scroll-driven image stack reveal with analog flash exposure & SVG grain texture overlays.",
    dependencies: ["framer-motion"],
    packagePath: "animated/ImageReveal.tsx",
    files: ["animated/ImageReveal.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      {
        name: "sensitivity",
        type: "number",
        default: 1400,
        description: "Scroll sensitivity factor (higher = slower reveal pace)",
        required: false,
        min: 400,
        max: 3000,
        step: 100,
      },
    ],
  },
  {
    name: "Image Parallax",
    slug: "image-parallax",
    category: "animated",
    description: "A smooth mouse-move and scroll-driven parallax image perspective effect.",
    dependencies: ["framer-motion"],
    packagePath: "animated/ImageParallax.tsx",
    files: ["animated/ImageParallax.tsx"],
    presentationStrategy: "center",
    propDefs: [
      {
        name: "depth",
        type: "number",
        default: 10,
        description: "Parallax travel depth in pixels",
        required: false,
        min: 0,
        max: 100,
        step: 5,
      },
      {
        name: "tiltAmount",
        type: "number",
        default: 5,
        description: "3D Yaw/Pitch card tilt amount in degrees",
        required: false,
        min: 0,
        max: 20,
        step: 1,
      },
    ],
  },
  {
    name: "Living Text",
    slug: "living-text",
    category: "animated",
    description: "Stretches, rotates, and pushes characters dynamically based on real-time cursor proximity.",
    dependencies: ["framer-motion"],
    packagePath: "animated/LivingText.tsx",
    files: ["animated/LivingText.tsx"],
    propDefs: [
      { name: "text", type: "string", default: "LIVING TEXT", description: "Text content to animate", required: true },
      { name: "radius", type: "number", default: 170, description: "Cursor influence radius in px", required: false, min: 50, max: 400, step: 10 },
      { name: "strength", type: "number", default: 46, description: "Movement offset strength in px", required: false, min: 5, max: 120, step: 1 },
      { name: "mode", type: "select", default: "all", description: "Proximity interaction mode", required: false, options: ["repel", "magnetize", "stretch", "rotate", "ripple", "all"] },
      { name: "liquify", type: "boolean", default: true, description: "Apply SVG turbulence liquification filter", required: false },
    ],
  },
  {
    name: "Spotlight Text",
    slug: "spotlight-text",
    category: "animated",
    description: "Debossed display text with a cursor-following spotlight clipped to glyph shapes and a minimal glowing bulb on the dot of 'i' and 'j'.",
    dependencies: [],
    packagePath: "animated/spotlight-text/SpotlightText.tsx",
    files: [
      "animated/spotlight-text/index.ts",
      "animated/spotlight-text/SpotlightText.tsx",
      "animated/spotlight-text/types.ts",
      "animated/spotlight-text/themes.ts",
      "animated/spotlight-text/hooks/useSpotlightHover.ts",
    ],
    presentationStrategy: "center",
    variants: [
      { name: "Default (Purple)", props: { text: "Antimetal", colorMode: "default" } },
      { name: "Yellow Tone", props: { text: "Antimetal", colorMode: "yellow" } },
    ],
    propDefs: [
      { name: "text", type: "string", default: "Antimetal", description: "Text content to render", required: true },
      { name: "colorMode", type: "select", default: "default", description: "Color illumination mode (default purple or yellow tone)", required: false, options: ["default", "yellow"] },
      { name: "spotlightRadius", type: "number", default: 140, description: "Spotlight radius in px", required: false, min: 60, max: 300, step: 10 },
      { name: "fontWeight", type: "number", default: 800, description: "Font weight", required: false, min: 400, max: 900, step: 100 },
    ],
  },
  {
    name: "Gravity Card Stack",
    slug: "gravity-card-stack",
    category: "animated",
    description: "Falling rigid body physics cards container that reacts to scroll triggers.",
    dependencies: ["matter-js", "gsap"],
    packagePath: "animated/GravityCardStack.tsx",
    files: ["animated/GravityCardStack.tsx"],
    propDefs: [
      { name: "className", type: "string", description: "Additional custom class names for the physics canvas container", required: false },
      { name: "gravity", type: "number", default: 1, min: 0, max: 3, step: 0.1, description: "Downwards 2D gravitational acceleration force in Matter.js world", required: false },
      { name: "restitution", type: "number", default: 0.7, min: 0, max: 1, step: 0.05, description: "Card bounce coefficient upon ground or wall impact", required: false },
      { name: "friction", type: "number", default: 0.1, min: 0, max: 0.5, step: 0.01, description: "Surface friction opposing card sliding motion", required: false },
    ],
  },

  {
    name: "Coverflow Carousel",
    slug: "coverflow-carousel",
    category: "animated",
    description: "A hardware-accelerated 3D coverflow carousel with continuous modular perspective transforms and comprehensive gesture tracking.",
    dependencies: ["framer-motion"],
    packagePath: "animated/coverflow/CoverflowCarousel.tsx",
    presentationStrategy: "center",
    files: [
      "animated/coverflow/CoverflowCarousel.tsx",
      "animated/coverflow/CoverflowCard.tsx",
      "animated/coverflow/types.ts",
      "animated/coverflow/utils.ts",
      "animated/coverflow/useCoverflow.ts",
    ],
    propDefs: [
      { name: "className", type: "string", description: "Additional wrapper CSS classes", required: false },
      { name: "rotate", type: "number", default: 30, min: 10, max: 60, step: 5, description: "3D Y-axis tilt rotation angle of adjacent album cards in degrees", required: false },
      { name: "depth", type: "number", default: 150, min: 50, max: 300, step: 10, description: "Perspective Z-translation setback distance in pixels", required: false },
    ],
  },
  {
    name: "Void Button",
    slug: "void-button",
    category: "buttons",
    description: "Pure black button that reveals a luxury gold gradient under the cursor via a smooth radial mask.",
    dependencies: ["framer-motion"],
    packagePath: "animated/VoidButton.tsx",
    files: ["animated/VoidButton.tsx"],
    propDefs: [
      { name: "variant", type: "select", default: "default", description: "Button style variant", required: false, options: ["default", "ambient", "neon-edge", "metallic-sheen", "glassmorphic"] },
      { name: "style", type: "select", default: "default", description: "Corner radius style of the button (pill renders rounded-full)", required: false, options: ["default", "pill"] },
      { name: "length", type: "number", default: 192, min: 120, max: 480, step: 4, description: "Horizontal length of the button in pixels", required: false },
      { name: "children", type: "string", default: "Default", description: "Button text label", required: false }
    ],
  },
  {
    name: "Brushed Titanium Button",
    slug: "brushed-titanium-button",
    category: "buttons",
    description: "Machined titanium texture with anisotropic highlight sweeps and reactive spotlight illumination.",
    dependencies: ["framer-motion"],
    packagePath: "animated/BrushedTitaniumButton.tsx",
    files: ["animated/BrushedTitaniumButton.tsx"],
    propDefs: [
      { name: "children", type: "string", default: "TITANIUM", description: "Button text label", required: false },
      { name: "length", type: "number", default: 192, min: 120, max: 480, step: 4, description: "Horizontal length of the button in pixels", required: false },
      { name: "disabled", type: "boolean", default: false, description: "Disable button state", required: false }
    ],
  },
  {
    name: "Liquid Gold Button",
    slug: "liquid-gold-button",
    category: "buttons",
    description: "Conic gradient rotating behind a frosted glass blur layer, with a 1px border that catches light only at the top.",
    dependencies: ["framer-motion"],
    packagePath: "animated/LiquidGoldButton.tsx",
    files: ["animated/LiquidGoldButton.tsx"],
    propDefs: [
      { name: "children", type: "string", default: "Liquid Gold", description: "Button text label", required: false }
    ],
  },
  {
    name: "Guilloche Button",
    slug: "guilloche-button",
    category: "buttons",
    description: "Watch dial Guilloché patterns generating Moire wave shapes under the cursor spotlight.",
    dependencies: ["framer-motion"],
    packagePath: "animated/GuillocheButton.tsx",
    files: ["animated/GuillocheButton.tsx"],
    propDefs: [
      { name: "children", type: "string", default: "Guilloché", description: "Button text label", required: false }
    ],
  },
  {
    name: "Button Alpha",
    slug: "button-alpha",
    category: "buttons",
    description: "High-friction matte polymer button with fine light-catching bevel borders and heavy Z-axis mechanical compression.",
    dependencies: ["framer-motion"],
    packagePath: "animated/ButtonAlpha.tsx",
    files: ["animated/ButtonAlpha.tsx"],
    propDefs: [
      { name: "children", type: "string", default: "ACTIVATE", description: "Button text label", required: false },
      { name: "shape", type: "select", default: "pill", description: "Button border shape", required: false, options: ["pill", "full", "square"] },
      { name: "theme", type: "select", default: "charcoal", description: "Color theme variation", required: false, options: ["charcoal", "danger", "tactical"] }
    ],
  },

  {
    name: "Pixel Melt",
    slug: "pixel-melt",
    category: "backgrounds",
    description: "A full-viewport pixel grid that glows and cools under cursor heat, leaving behind a slow melt trail.",
    dependencies: [],
    packagePath: "backgrounds/PixelMelt.tsx",
    files: ["backgrounds/PixelMelt.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "pixelSize", type: "number", default: 12, min: 4, max: 32, step: 2, description: "Width and height of each digital pixel block in pixels", required: false },
      { name: "meltSpeed", type: "number", default: 1, min: 0.2, max: 3, step: 0.1, description: "Drip acceleration rate of cascading molten pixels", required: false },
      { name: "interactive", type: "boolean", default: true, description: "Whether pointer hover activates localized pixel melting", required: false },
      { name: "className", type: "string", description: "Optional layout container classes", required: false },
    ],
  },
  {
    name: "Breathing Grid",
    slug: "breathing-grid",
    category: "backgrounds",
    description: "An orthogonal grid with a slow left-to-right traveling wave, with local brightness boost near the cursor.",
    dependencies: [],
    packagePath: "backgrounds/BreathingGrid.tsx",
    files: ["backgrounds/BreathingGrid.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "gridSize", type: "number", default: 40, min: 20, max: 80, step: 5, description: "Spacing between background grid nodes in pixels", required: false },
      { name: "baseOpacity", type: "number", default: 0.1, min: 0.02, max: 0.5, step: 0.02, description: "Resting ambient opacity of inactive grid intersections", required: false },
      { name: "cycleDuration", type: "number", default: 8000, min: 2000, max: 15000, step: 500, description: "Full duration of sinusoidal ambient brightness pulse in milliseconds", required: false },
      { name: "className", type: "string", description: "Additional wrapper CSS classes", required: false },
    ],
  },
  {
    name: "Breathing Background",
    slug: "breathing-background",
    category: "backgrounds",
    description: "An atmospheric sweeping pattern background with breathing backlight glow, vignette layer, and dynamic pattern options (diagonal, stripes, dots, grid).",
    dependencies: ["framer-motion"],
    packagePath: "backgrounds/BreathingBackground.tsx",
    files: ["backgrounds/BreathingBackground.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "preset", type: "select", default: "indigo", description: "Curated color theme preset", required: false, options: ["indigo", "cyberpunk", "emerald", "amber", "custom"] },
      { name: "patternVariant", type: "select", default: "diagonal", description: "Geometric pattern background variant", required: false, options: ["diagonal", "stripes", "dots", "grid"] },
      { name: "duration", type: "number", default: 8, description: "Breathing loop speed in seconds", required: false, min: 2, max: 20, step: 1 },
      { name: "patternSize", type: "number", default: 16, description: "Pattern tile size in pixels", required: false, min: 6, max: 48, step: 2 },
      { name: "angle", type: "number", default: 315, description: "Gradient pattern angle in degrees", required: false, min: 0, max: 360, step: 15 },
      { name: "vignette", type: "boolean", default: true, description: "Enable soft edge and corner vignette mask", required: false },
    ],
  },
  {
    name: "Floating Embers",
    slug: "floating-embers",
    category: "backgrounds",
    description: "Glowing ember particles that float upward with a gentle sway, reacting subtly to cursor and scroll.",
    dependencies: [],
    packagePath: "backgrounds/FloatingEmbers.tsx",
    files: ["backgrounds/FloatingEmbers.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "maxParticles", type: "number", default: 400, min: 50, max: 800, step: 25, description: "Maximum active rising fire ember particles rendered", required: false },
      { name: "mouseRadius", type: "number", default: 200, min: 50, max: 400, step: 25, description: "Proximity radius for pointer wind deflection in pixels", required: false },
      { name: "mouseForce", type: "number", default: 0.02, min: 0.005, max: 0.08, step: 0.005, description: "Deflection impulse applied when cursor moves through particles", required: false },
      { name: "className", type: "string", description: "Additional wrapper CSS classes", required: false },
    ],
  },
  {
    name: "Spotlight Grid",
    slug: "spotlight-grid",
    category: "backgrounds",
    description: "A dark grid with decorative tech icons and a dual-layer mouse-following spotlight effect using screen and color-dodge blend modes.",
    dependencies: [],
    packagePath: "backgrounds/SpotlightGrid.tsx",
    files: ["backgrounds/SpotlightGrid.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "children", type: "React.ReactNode", description: "Foreground content rendered above interactive spotlight grid", required: false },
      { name: "cellSize", type: "number", default: 64, min: 32, max: 128, step: 8, description: "Dimensions of each 3D grid cell in pixels", required: false },
      { name: "spotlightColor", type: "color", default: "#ffffff", description: "Accent illumination color of mouse follower spotlight", required: false },
      { name: "className", type: "string", description: "Additional wrapper CSS classes", required: false },
    ],
  },
  {
    name: "Lumina Wave",
    slug: "lumina-wave",
    category: "backgrounds",
    description: "An atmospheric WebGL background rendering undulating wave patterns resembling an aurora, featuring interactive mouse-bending and color personalization.",
    dependencies: [],
    packagePath: "backgrounds/LuminaWave.tsx",
    files: ["backgrounds/LuminaWave.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "speed", type: "number", default: 1.0, min: 0.2, max: 3.0, step: 0.1, description: "Animation progression speed multiplier for mathematical wave cycles", required: false },
      { name: "intensity", type: "number", default: 1.0, min: 0.2, max: 2.5, step: 0.1, description: "Luminance and contrast multiplier of glowing wave lines", required: false },
      { name: "colorPrimary", type: "color", default: "#2563eb", description: "Hex color code for primary wave frequency", required: false },
      { name: "colorSecondary", type: "color", default: "#6610f2", description: "Hex color code for secondary wave frequency", required: false },
      { name: "quality", type: "select", default: "medium", description: "Canvas internal render resolution multiplier", required: false, options: ["high", "medium", "low"] },
      { name: "mouseReactivity", type: "number", default: 1.0, min: 0, max: 2, step: 0.1, description: "Sensitivity of wave distortion to pointer movement", required: false },
      { name: "className", type: "string", description: "Additional layout styling classes", required: false },
    ],
  },
  {
    name: "Matrix Rain",
    slug: "matrix-rain",
    category: "backgrounds",
    description: "A canvas-driven digital rain simulation displaying streaming glowing characters and icons in a premium monochrome aesthetic.",
    dependencies: [],
    packagePath: "backgrounds/MatrixRain.tsx",
    files: ["backgrounds/MatrixRain.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "speed", type: "number", default: 1.0, description: "Falling speed multiplier", required: false, min: 0.2, max: 4, step: 0.1 },
      { name: "density", type: "number", default: 1.0, description: "Stream column density factor", required: false, min: 0.2, max: 3, step: 0.1 },
      { name: "fontSize", type: "number", default: 16, description: "Size of characters in pixels", required: false, min: 10, max: 36, step: 2 },
      { name: "decayRate", type: "number", default: 0.05, description: "Trail fade overlay speed", required: false, min: 0.01, max: 0.2, step: 0.01 },
      { name: "glowStrength", type: "number", default: 8, description: "Neon blur glow radius of stream head", required: false, min: 0, max: 20, step: 2 },
      { name: "opacity", type: "number", default: 0.35, description: "Canvas transparency opacity", required: false, min: 0.1, max: 1.0, step: 0.05 },
      { name: "color", type: "color", default: "#525252", description: "Color of trailing code segments", required: false },
      { name: "glowColor", type: "color", default: "#ffffff", description: "Color of leading glowing header symbol", required: false }
    ],
  },



  {
    name: "Anisotropic Knob",
    slug: "anisotropic-knob",
    category: "primitives",
    description: "Machined metal rotary dial knob component with dynamic rotating anisotropic highlights, snapper increments, and accessibility controls.",
    dependencies: ["framer-motion"],
    packagePath: "animated/AnisotropicKnob.tsx",
    files: ["animated/AnisotropicKnob.tsx"],
    propDefs: [
      { name: "variant", type: "select", default: "slider", description: "Knob behavior mode", required: false, options: ["slider", "infinite"] },
      { name: "min", type: "number", default: 0, description: "Minimum slider value", required: false, min: -100, max: 100, step: 10 },
      { name: "max", type: "number", default: 100, description: "Maximum slider value", required: false, min: 10, max: 500, step: 10 },
      { name: "step", type: "number", default: 1, description: "Snap increments", required: false, min: 1, max: 50, step: 1 },
      { name: "size", type: "number", default: 112, description: "Diameter of the knob in pixels", required: false, min: 80, max: 200, step: 10 },
      { name: "label", type: "string", default: "VOLUME", description: "Label text", required: false },
      { name: "sound", type: "boolean", default: true, description: "Enable click feedback sound", required: false },
    ],
  },

  {
    name: "Vault",
    slug: "laser-vault-password",
    category: "widgets",
    description: "Passcode vault keypad with laser-etch cooling characters, dynamic cursor sweeps, tactile clicks, container rattles, and friction-metal creak alarms.",
    dependencies: ["framer-motion", "lucide-react"],
    packagePath: "animated/LaserVaultPassword.tsx",
    files: ["animated/LaserVaultPassword.tsx"],
    propDefs: [
      { name: "onUnlock", type: "() => void", description: "Callback fired when safe combination or password unlocks successfully", required: false },
      { name: "soundEffects", type: "boolean", default: true, description: "Whether to synthesize tactile mechanical vault gear sounds", required: false },
      { name: "variant", type: "select", default: "cyber-laser", description: "Skeuomorphic chassis material finish", required: false, options: ["ambient", "neon-edge", "metallic-sheen", "glassmorphic", "cyber-laser", "classic-gold"] },
      { name: "className", type: "string", description: "Custom styling classes for safe dial container", required: false },
    ],
  },
  {
    name: "Premium Hero",
    slug: "premium-hero",
    category: "animated",
    description: "Interactive Hero Section featuring floating 3D cards, typewriter search, spring CTA, and paper-notebook grid aesthetics.",
    dependencies: ["framer-motion", "lucide-react"],
    packagePath: "animated/PremiumHero.tsx",
    files: ["animated/PremiumHero.tsx"],
    presentationStrategy: "cover",
    propDefs: [
      { name: "title", type: "string", default: "Crafted with Precision", description: "Primary editorial headline rendered with serif typography", required: false },
      { name: "subtitle", type: "string", default: "High-friction UI components designed for high-end web experiences", description: "Secondary description paragraph below main headline", required: false },
      { name: "ctaText", type: "string", default: "Explore Studio", description: "Label text for primary action CTA button", required: false },
      { name: "onSearchSubmit", type: "(query: string) => void", description: "Callback fired when hero search bar query is submitted", required: false },
      { name: "className", type: "string", description: "Custom classes for hero wrapper layout", required: false },
    ],
  },
  {
    name: "Dot Matrix",
    slug: "dot-matrix",
    category: "animated",
    description: "Highly optimized, programmable LED dot matrix display supporting Perlin noise, typewriter bitmaps, Web Audio integration, interactive cursor repelling, and custom plugin architectures.",
    dependencies: ["framer-motion"],
    packagePath: "animated/DotMatrix.tsx",
    files: [
      "matrix/DotMatrix.tsx",
      "matrix/Dot.tsx",
      "matrix/types.ts",
      "matrix/animations/plugins.ts",
      "matrix/animations/index.ts",
      "matrix/hooks/useMouseInfluence.ts",
      "matrix/hooks/useRAF.ts",
      "matrix/utils/distance.ts",
      "matrix/utils/noise.ts",
      "matrix/utils/bitmap.ts",
    ],
    propDefs: [
      { name: "animation", type: "select", default: "scroll-text", description: "Animation mode", required: false, options: ["wave", "text", "scroll-text", "clock", "equalizer", "noise", "sparkle", "ripple", "snake", "rain"] },
      { name: "text", type: "string", default: "VOID UI", description: "Text content (for text/scroll-text modes)", required: false },
      { name: "columns", type: "number", default: 44, description: "Number of dot columns", required: false, min: 10, max: 80, step: 1 },
      { name: "rows", type: "number", default: 12, description: "Number of dot rows", required: false, min: 4, max: 24, step: 1 },
      { name: "color", type: "color", default: "#e7e5df", description: "Active dot color", required: false },
      { name: "speed", type: "number", default: 1, description: "Animation speed multiplier", required: false, min: 0.1, max: 5, step: 0.1 },
      { name: "glow", type: "boolean", default: true, description: "Enable glow effect on dots", required: false },
    ],
  },

  {
    name: "Scroll Progress",
    slug: "scroll-progress",
    category: "animated",
    description: "A vertical dynamic scrollbar overlay with interactive tick mark animations, dragging controls, and velocity-based stretching/glow.",
    dependencies: ["framer-motion"],
    packagePath: "animated/scrollprogress/ScrollProgress.tsx",
    files: [
      "animated/scrollprogress/ScrollProgress.tsx",
      "animated/scrollprogress/Tick.tsx",
      "animated/scrollprogress/useScrollProgress.ts",
      "animated/scrollprogress/types.ts",
      "animated/scrollprogress/utils.ts",
    ],
    propDefs: [
      { name: "ticks", type: "number", default: 42, description: "Number of vertical tick marks", required: false, min: 10, max: 100, step: 1 },
      { name: "color", type: "color", default: "#a855f7", description: "Color of the active scroll indicator", required: false },
      { name: "glow", type: "boolean", default: true, description: "Enable glow halo around the active indicator", required: false },
      { name: "height", type: "number", default: 44, description: "Thickness (width) of the scrollbar in pixels", required: false, min: 20, max: 100, step: 2 },
      { name: "width", type: "number", default: 320, description: "Length (height) of the scrollbar in pixels", required: false, min: 150, max: 600, step: 10 },
      { name: "variant", type: "select", default: "default", description: "Design variant of the scroll-bar", required: false, options: ["default", "prominent", "inverted"] },
    ],
  },

  {
    name: "Now Playing Card",
    slug: "now-playing-card",
    category: "animated",
    description: "A Spotify-style vinyl player card powered by Last.fm API that dynamically retrieves real-time listening history with vinyl spin animations.",
    dependencies: ["react-icons"],
    packagePath: "animated/NowPlayingCard.tsx",
    files: ["animated/NowPlayingCard.tsx"],
    propDefs: [
      { name: "song", type: "Song", description: "Currently playing track object containing title, artist, album, image, songUrl, and isPlaying state", required: true },
      { name: "className", type: "string", description: "Custom classes for card link container", required: false },
    ],
  },
  {
    name: "Wheel Picker",
    slug: "wheel-picker",
    category: "animated",
    description: "Premium physical-feeling 3D wheel picker with momentum dragging, spring snapping, and mechanical Web Audio crown clicks.",
    dependencies: ["framer-motion"],
    packagePath: "animated/WheelPicker.tsx",
    files: [
      "animated/WheelPicker.tsx",
      "animated/react-wheel-picker/index.ts",
      "animated/react-wheel-picker/types.ts",
      "animated/react-wheel-picker/components/WheelPicker.tsx",
      "animated/react-wheel-picker/components/Cylinder.tsx",
      "animated/react-wheel-picker/components/WheelItem.tsx",
      "animated/react-wheel-picker/components/SelectionOverlay.tsx",
      "animated/react-wheel-picker/hooks/useCylinderTransform.ts",
      "animated/react-wheel-picker/hooks/useInfiniteLoop.ts",
      "animated/react-wheel-picker/hooks/useAudio.ts",
      "animated/react-wheel-picker/hooks/useWheel.ts",
      "animated/react-wheel-picker/hooks/useMomentum.ts",
      "animated/react-wheel-picker/hooks/useSnap.ts",
      "animated/react-wheel-picker/utils/physics.ts",
      "animated/react-wheel-picker/utils/audio.ts",
      "animated/react-wheel-picker/utils/math.ts",
    ],
    propDefs: [
      { name: "variant", type: "select", default: "glass", description: "Visual style of the picker", required: false, options: ["glass", "minimal", "void"] },
      { name: "loop", type: "boolean", default: false, description: "Allow infinite looping through items", required: false },
      { name: "sound", type: "boolean", default: true, description: "Play mechanical click sound on selection change", required: false },
      { name: "disabled", type: "boolean", default: false, description: "Disable interaction and pointer events", required: false },
      { name: "itemHeight", type: "number", default: 40, description: "Height of each item in pixels", required: false, min: 20, max: 100, step: 1 },
      { name: "visibleItems", type: "number", default: 5, description: "Number of visible items in the viewport", required: false, min: 3, max: 11, step: 1 },
      { name: "perspective", type: "number", default: 1000, description: "3D perspective depth in pixels", required: false, min: 200, max: 2000, step: 50 },
    ],
  },
  {
    name: "Weapon Wheel",
    slug: "weapon-wheel",
    category: "animated",
    description: "Premium GTA V-inspired selection wheel designed for development tools, featuring interactive SVG slices, Tabler icons, mechanical clicks, and live stats dashboards.",
    dependencies: ["framer-motion", "@tabler/icons-react", "devicons-react"],
    packagePath: "animated/WeaponWheel.tsx",
    files: ["animated/WeaponWheel.tsx"],
    propDefs: [
      { name: "variant", type: "select", default: "default", description: "Visual style of the weapon wheel canvas", required: false, options: ["default", "beveled"] },
      { name: "inline", type: "boolean", default: true, description: "Whether to render inline in the page canvas instead of a full-screen popup modal overlay", required: false },
      { name: "triggerKey", type: "string", default: "q", description: "Keyboard key to hold to trigger the selection overlay in modal mode", required: false },
    ],
  },

  {
    name: "Hero Landing",
    slug: "hero",
    category: "animated",
    description: "Highly configurable, responsive portfolio hero landing page with technical grids and interactive pixel art decorations.",
    dependencies: ["framer-motion"],
    packagePath: "animated/Hero.tsx",
    files: ["animated/Hero.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "name", type: "string", default: "stephanie", description: "Giant display wordmark name text", required: true },
      { name: "bgColor", type: "color", default: "#1E3FEB", description: "Saturated canvas background color", required: false },
      { name: "gridOpacity", type: "number", default: 0.06, description: "Line opacity of repeating background grids", required: false, min: 0.0, max: 0.3, step: 0.01 },
      { name: "fontFamily", type: "select", default: "instrument", description: "Primary serif display typeface", required: false, options: ["instrument", "fraunces", "playfair", "newsreader", "custom"] },
      { name: "monoFontFamily", type: "select", default: "dotgothic", description: "Monospace labels/nav typeface", required: false, options: ["dotgothic", "silkscreen", "pressstart", "vt323", "pixelify", "jersey"] },
      { name: "iconVariant", type: "select", default: "flower", description: "Pixel art decoration icon shape", required: false, options: ["flower", "heart", "star", "skull", "crown", "ghost", "none"] },
      { name: "iconAnimation", type: "select", default: "static", description: "Interactive animation variant behavior", required: false, options: ["static", "hover-bloom", "idle-loop", "scroll-linked", "clickable"] },
      { name: "iconPosition", type: "select", default: "inline", description: "Visual alignment relative to wordmark name text", required: false, options: ["inline", "top-right", "bottom-right", "top-left", "bottom-left"] },
      { name: "iconSize", type: "number", default: 36, description: "Size dimensions of the central pixel icon", required: false, min: 16, max: 80, step: 4 },
      { name: "iconRotation", type: "number", default: 0, description: "Initial rotation tilt angle in degrees", required: false, min: -360, max: 360, step: 15 },
      { name: "introduction", type: "string", default: "I build high-end interactive visual systems and graphics for digital exhibitions, museums, and products.", description: "Sub-headline description paragraph below name", required: false },
      { name: "pixelDensity", type: "select", default: "medium", description: "Count of floating pixel crosses on canvas", required: false, options: ["sparse", "medium", "dense"] },
      { name: "enableParallax", type: "boolean", default: true, description: "Mouse cursor follow spring parallax effect", required: false },
      { name: "animationSpeed", type: "select", default: "normal", description: "Crosses floating speed multiplier", required: false, options: ["slow", "normal", "fast"] },
      { name: "backgroundIconVariant", type: "select", default: "cross", description: "Pixel art icon shape used uniformly across background floating layout", required: false, options: ["flower", "heart", "star", "skull", "crown", "ghost", "cross"] },
      { name: "backgroundIconCount", type: "number", default: 8, description: "Total count of background floating icons to scatter", required: false, min: 2, max: 24, step: 1 },
    ]
  },
  {
    name: "Expand On Hover",
    slug: "expand-on-hover",
    category: "animated",
    description: "A stack of compact preview cards that smoothly expand into immersive content panels on hover, featuring physical parting animations and 3D pointer tracking.",
    dependencies: ["framer-motion"],
    packagePath: "animated/expand-on-hover/components/expand-on-hover/ExpandOnHover.tsx",
    files: [
      "animated/expand-on-hover/index.ts",
      "animated/expand-on-hover/types.ts",
      "animated/expand-on-hover/hooks/useExpand.ts",
      "animated/expand-on-hover/components/expand-on-hover/ExpandOnHover.tsx",
      "animated/expand-on-hover/components/expand-on-hover/Preview.tsx",
      "animated/expand-on-hover/components/expand-on-hover/CardContent.tsx",
      "animated/expand-on-hover/components/expand-on-hover/ExpandCard.tsx",
    ],
    propDefs: [
      { name: "animation", type: "select", default: "spring", description: "Expansion transition physics", required: false, options: ["spring", "smooth"] },
      { name: "variant", type: "select", default: "modern", description: "Card visual style", required: false, options: ["modern", "minimal"] },
      { name: "expandHeight", type: "number", default: 440, description: "Height of expanded card (px)", required: false, min: 280, max: 600, step: 20 },
      { name: "collapsedHeight", type: "number", default: 64, description: "Height of collapsed card (px)", required: false, min: 48, max: 100, step: 4 },
      { name: "borderRadius", type: "number", default: 20, description: "Border radius of cards (px)", required: false, min: 0, max: 36, step: 2 },
      { name: "gap", type: "number", default: 12, description: "Gap between cards (px)", required: false, min: 4, max: 32, step: 2 },
    ],
  },
  {
    name: "Text Shuffle",
    slug: "text-shuffle",
    category: "animated",
    description: "A text animation component that shuffles characters with multiple variants including cipher, scramble, and typewriter effects.",
    dependencies: ["framer-motion"],
    packagePath: "animated/text-shuffle/TextShuffle.tsx",
    files: [
      "animated/text-shuffle/index.ts",
      "animated/text-shuffle/TextShuffle.tsx",
      "animated/text-shuffle/AnimatedWord.tsx",
      "animated/text-shuffle/types.ts",
      "animated/text-shuffle/hooks/useShuffleVariants.ts",
      "animated/text-shuffle/hooks/useShuffleCycle.ts",
      "animated/text-shuffle/utils/splitCharacters.ts",
      "animated/text-shuffle/utils/timing.ts",
    ],
    propDefs: [
      { name: "variant", type: "select", default: "blurReveal", description: "Visual morph variant", required: false, options: ["scramble", "wave", "glitch", "elastic", "flipIn", "blurReveal"] },
      { name: "duration", type: "number", default: 2200, description: "Display duration per word (ms)", required: false, min: 500, max: 8000, step: 100 },
      { name: "transition", type: "number", default: 700, description: "Transition duration between words (ms)", required: false, min: 100, max: 2000, step: 50 },
      { name: "loop", type: "boolean", default: true, description: "Loop cycling infinitely", required: false },
      { name: "pauseOnHover", type: "boolean", default: false, description: "Pause on hover", required: false },
      { name: "cursorBlink", type: "boolean", default: false, description: "Show blinking cursor", required: false },
      { name: "uppercase", type: "boolean", default: false, description: "Force uppercase", required: false },
      { name: "outline", type: "boolean", default: false, description: "Render text as outline stroke", required: false },
      { name: "fontSize", type: "string", default: "clamp(2.5rem,8vw,6rem)", description: "Font size CSS value", required: false },
    ],
  },
  {
    name: "Cards",
    slug: "cards",
    category: "animated",
    description: "A fanned deck of dark editorial cards with B&W images, prismatic top-border highlights, spring-physics animations, and an expand-on-click description reveal.",
    dependencies: ["framer-motion"],
    packagePath: "animated/Cards.tsx",
    files: ["animated/Cards.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "className", type: "string", description: "Additional layout wrapper classes", required: false },
      { name: "spacing", type: "number", default: 230, min: 150, max: 350, step: 10, description: "Horizontal offset spacing between overlapping card deck items in pixels", required: false },
      { name: "perspective", type: "boolean", default: true, description: "Enables 3D perspective depth transforms on card hover", required: false },
    ],
  },
  {
    name: "Simple Card",
    slug: "simple-card",
    category: "animated",
    description: "A single dark editorial card with a padded B&W image, prismatic top-border highlight, Instrument Serif title pinned to the bottom, and an expand-on-click description reveal.",
    dependencies: ["framer-motion"],
    packagePath: "animated/SimpleCard.tsx",
    files: ["animated/SimpleCard.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "title", type: "string", default: "Working Knowledge", description: "Card title heading displayed at the bottom", required: true },
      { name: "description", type: "string", default: "Practical skills and insights gained through hands-on experience.", description: "Card body explanatory text revealed on expand", required: false },
      { name: "imageUrl", type: "string", description: "Optional thumbnail or banner image URL", required: false },
      { name: "accent", type: "string", default: "from-transparent to-transparent", description: "Tailwind gradient string for ambient light glow", required: false },
      { name: "topBorderColor", type: "string", default: "rgba(255,255,255,0.18)", description: "Top specular catchlight border color", required: false },
      { name: "className", type: "string", description: "Custom container classes", required: false },
    ],
  },
  {
    name: "Flickering Grid Playground",
    slug: "flickering-grid-playground",
    category: "animated",
    description: "An interactive cockpit controller playground for experimenting with grid sizing, gaps, flicker chance, and curated presets.",
    dependencies: [],
    packagePath: "animated/FlickeringGrid.tsx",
    files: ["animated/FlickeringGrid.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "squareSize", type: "number", default: 4, min: 2, max: 16, step: 1, description: "Size of individual square grid pixels in px", required: false },
      { name: "gridGap", type: "number", default: 6, min: 2, max: 20, step: 1, description: "Spacing between adjacent square pixels in px", required: false },
      { name: "flickerChance", type: "number", default: 0.3, min: 0.05, max: 0.9, step: 0.05, description: "Probability per frame that an active pixel modulates opacity", required: false },
      { name: "color", type: "color", default: "#6b7280", description: "Hex color code for the rendered pixel squares", required: false },
      { name: "maxOpacity", type: "number", default: 0.4, min: 0.1, max: 1, step: 0.05, description: "Peak brightness opacity value when flickering", required: false },
      { name: "className", type: "string", description: "Custom wrapper class names", required: false },
    ],
  },
  {
    name: "Dot Pattern Playground",
    slug: "dot-pattern-playground",
    category: "animated",
    description: "An interactive cockpit controller playground for dynamic dot sizes, gaps, custom swatches, and interactive spotlight masking.",
    dependencies: [],
    packagePath: "animated/DotPattern.tsx",
    files: ["animated/DotPattern.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "width", type: "number", default: 16, min: 8, max: 48, step: 2, description: "Horizontal pattern repeat tile pitch in pixels", required: false },
      { name: "height", type: "number", default: 16, min: 8, max: 48, step: 2, description: "Vertical pattern repeat tile pitch in pixels", required: false },
      { name: "cx", type: "number", default: 1, min: 0.5, max: 4, step: 0.5, description: "Center X coordinate of the circle dot within pattern tile", required: false },
      { name: "cy", type: "number", default: 1, min: 0.5, max: 4, step: 0.5, description: "Center Y coordinate of the circle dot within pattern tile", required: false },
      { name: "cr", type: "number", default: 1, min: 0.5, max: 4, step: 0.5, description: "Radius of each individual circular dot in pixels", required: false },
      { name: "className", type: "string", description: "Custom SVG styling classes", required: false },
    ],
  },

  {
    name: "Animated Icons 1",
    slug: "animated-icons-1",
    category: "animated",
    description: "Nine Tabler icons in small monochrome black cards. Click any card to fire its unique animation — triple spin, nuclear collapse, hex facet snap, supernova burst, lemniscate shudder, glitch disintegrate, lightning strike, helix flip, or vortex implosion. Pure monochrome, no color, no shadows.",
    dependencies: ["framer-motion", "@tabler/icons-react"],
    packagePath: "animated/Loaders1.tsx",
    files: ["animated/Loaders1.tsx", "animated/LoaderCard.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "cardSize", type: "number", default: 160, min: 100, max: 240, step: 10, description: "Outer card width and height dimensions in pixels", required: false },
      { name: "iconSize", type: "number", default: 48, min: 24, max: 80, step: 4, description: "Vector icon size in pixels", required: false },
      { name: "className", type: "string", description: "Additional wrapper classes", required: false },
    ],
  },
  {
    name: "Marquee",
    slug: "marquee",
    category: "animated",
    description: "An infinite scrolling marquee section utilizing custom edit-dashed cards and compact icon tiles with speed, direction, and corner blur settings.",
    dependencies: ["framer-motion", "@tabler/icons-react"],
    packagePath: "animated/Marquee.tsx",
    files: ["animated/Marquee.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "variant", type: "select", default: "default", description: "Display variant style", options: ["default", "icon"], required: false },
      { name: "cardVariant", type: "select", default: "dashed", description: "Design style of marquee cards", options: ["dashed", "bevel"], required: false },
      { name: "direction", type: "select", default: "right-to-left", description: "Movement direction of the track", options: ["left-to-right", "right-to-left", "up-to-down", "down-to-up"], required: false },
      { name: "speed", type: "number", default: 25, description: "Full loop animation duration in seconds", required: false, min: 5, max: 120, step: 1 },
      { name: "blurCorners", type: "boolean", default: true, description: "Whether to render gradient blur fade on container ends", required: false },
      { name: "pauseOnHover", type: "boolean", default: true, description: "Pause marquee sliding on mouse hover", required: false },
    ],
  },
  {
    name: "Marquee 2",
    slug: "marquee-2",
    category: "animated",
    description: "An infinite curved path marquee section animating official colored brand icons along a custom bezier SVG path.",
    dependencies: ["framer-motion", "devicons-react"],
    packagePath: "animated/Marquee2.tsx",
    files: ["animated/Marquee2.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "variant", type: "select", default: "wave", description: "Curved motion path style", options: ["wave", "arch", "valley", "double-wave", "straight"], required: false },
      { name: "showTitleOnHover", type: "boolean", default: true, description: "Display brand title badge on mouse hover", required: false },
      { name: "speed", type: "number", default: 1, description: "Animation speed multiplier", required: false, min: 0.2, max: 5, step: 0.1 },
      { name: "pauseOnHover", type: "boolean", default: true, description: "Pause marquee sliding on mouse hover", required: false },
    ],
  },
  {
    name: "Accordion",
    slug: "accordion",
    category: "animated",
    description: "A tactile 3D beveled accordion stack with smooth sequential close-then-open panel transitions and rotating chevrons.",
    dependencies: ["framer-motion"],
    packagePath: "animated/Accordion.tsx",
    files: ["animated/Accordion.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "allowMultiple", type: "boolean", default: false, description: "Allow multiple panels open at once", required: false },
    ],
  },
  {
    name: "Sticker Card",
    slug: "sticker-card",
    category: "animated",
    description: "An interactive card that scatters bouncy physics-based stickers all over the viewport on hover.",
    dependencies: ["framer-motion", "lucide-react", "@tabler/icons-react"],
    packagePath: "animated/StickerCard.tsx",
    files: ["animated/StickerCard.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "numStickers", type: "number", default: 7, description: "Number of scattered stickers to render", required: false, min: 5, max: 10, step: 1 },
    ],
  },
  {
    name: "Datepicker",
    slug: "datepicker",
    category: "animated",
    description: "A skeuomorphic 3D beveled calendar date picker with synth mechanical click sound feedback.",
    dependencies: ["framer-motion", "@tabler/icons-react"],
    packagePath: "animated/Datepicker.tsx",
    files: ["animated/Datepicker.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "glowColor", type: "select", default: "none", description: "Neon glow color behind the datepicker", options: ["none", "blue", "white"], required: false },
    ],
  },
  {
    name: "NavBar1",
    slug: "navbar-1",
    category: "animated",
    description: "A floating horizontal navigation panel console with sliding tabs, active status glows, and search well.",
    dependencies: ["framer-motion", "@tabler/icons-react"],
    packagePath: "animated/NavBar1.tsx",
    files: ["animated/NavBar1.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "statusColor", type: "select", default: "emerald", description: "Status pulse dot indicator theme color", required: false, options: ["emerald", "cyan", "rose"] },
      { name: "className", type: "string", description: "Additional navbar container styling classes", required: false },
    ],
  },

  {
    name: "ForgeUI Landing",
    slug: "forgeui-landing",
    category: "animated",
    description: "Sleek dark landing page hero section with radial spotlights, customizable calls to action, and interactive social/tech stack footer.",
    dependencies: ["lucide-react", "framer-motion"],
    packagePath: "animated/ForgeUILanding.tsx",
    files: ["animated/ForgeUILanding.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "forgeUiUrl", type: "string", default: "https://forgeui.in", description: "Destination redirect URL for primary link button", required: false },
      { name: "onDocumentation", type: "() => void", description: "Callback fired when clicking the 'Documentation' action button", required: false },
      { name: "className", type: "string", description: "Optional layout wrapper classes", required: false },
    ],
  },

  {
    name: "Rays Landing",
    slug: "rays-landing",
    category: "animated",
    description: "Interactive portfolio landing page showcasing an overhead WebGL light-ray beam background, floating liquid-glass navigation, and role cycler.",
    dependencies: ["lucide-react"],
    packagePath: "animated/RaysLanding.tsx",
    files: ["animated/RaysLanding.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "name", type: "string", default: "Ajinkya", description: "Name displayed in headline", required: false },
      { name: "raysColor", type: "color", default: "#ffffff", description: "Hex color for WebGL light rays", required: false },
      { name: "raysSpeed", type: "number", default: 1.0, description: "Speed multiplier for ray animation", required: false, min: 0.1, max: 5.0, step: 0.1 },
      { name: "lightSpread", type: "number", default: 1.0, description: "Angular spread of rays", required: false, min: 0.1, max: 3.0, step: 0.1 },
      { name: "rayLength", type: "number", default: 2.0, description: "Reach distance of rays", required: false, min: 0.5, max: 4.0, step: 0.1 },
      { name: "followMouse", type: "boolean", default: true, description: "Enable mouse tracking for rays", required: false },
    ],
  },
  {
    name: "Breathing Scale Card",
    slug: "breathing-scale-card",
    category: "animated",
    description: "An ambient scale card component featuring overshooting corner border lines, a soft vignette mask, breathing backlight glows, and sweeping geometric pattern animations.",
    dependencies: ["framer-motion"],
    packagePath: "animated/BreathingScaleCard.tsx",
    files: ["animated/BreathingScaleCard.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "preset", type: "select", default: "indigo", description: "Curated color theme preset", required: false, options: ["indigo", "cyberpunk", "emerald", "amber", "custom"] },
      { name: "patternVariant", type: "select", default: "diagonal", description: "Geometric pattern background variant", required: false, options: ["diagonal", "stripes", "dots", "grid"] },
      { name: "duration", type: "number", default: 7, description: "Breathing loop speed in seconds", required: false, min: 2, max: 20, step: 1 },
      { name: "patternSize", type: "number", default: 10, description: "Pattern tile size in pixels", required: false, min: 4, max: 40, step: 2 },
      { name: "vignette", type: "boolean", default: true, description: "Enable soft edge and corner vignette mask", required: false },
    ],
  },
  {
    name: "GitHub Heatmap",
    slug: "github-heatmap",
    category: "animated",
    description: "An ultra-polished GitHub contribution heatmap featuring live data fetching for @ajinkya-cell, streak stats, theme presets, interactive tooltips, and month focus filtering.",
    dependencies: ["framer-motion"],
    packagePath: "animated/GithubHeatmap.tsx",
    files: ["animated/GithubHeatmap.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "username", type: "string", default: "ajinkya-cell", description: "GitHub username to fetch contributions for", required: false },
      { name: "preset", type: "select", default: "emerald", description: "Color theme preset", required: false, options: ["emerald", "obsidian", "cyberpunk", "indigo", "custom"] },
      { name: "showStats", type: "boolean", default: true, description: "Display total contributions, streak, and peak day stats", required: false },
      { name: "showLegend", type: "boolean", default: true, description: "Display bottom contribution scale legend", required: false },
      { name: "showMonthLabels", type: "boolean", default: true, description: "Display clickable month headers", required: false },
      { name: "showDayLabels", type: "boolean", default: true, description: "Display day of week labels", required: false },
    ],
  },
  {
    name: "Developer ID Card",
    slug: "developer-id-card",
    category: "animated",
    description: "An ultra-polished, feature-packed 3D Developer ID Card featuring GitHub profile image, live local clock, tech stack badges, social links, and 3D metallic presets.",
    dependencies: ["framer-motion"],
    packagePath: "animated/DeveloperIdCard.tsx",
    files: ["animated/DeveloperIdCard.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "name", type: "string", default: "Ajinkya", description: "Display name", required: false },
      { name: "username", type: "string", default: "ajinkya-cell", description: "GitHub handle", required: false },
      { name: "role", type: "string", default: "Full-Stack Engineer & UI Architect", description: "Developer title or role", required: false },
      { name: "location", type: "string", default: "San Francisco, CA", description: "Location text", required: false },
      { name: "bio", type: "string", default: "Architecting high-performance UI systems, agentic coding workflows, and futuristic web interfaces.", description: "Custom intro bio text", required: false },
      { name: "preset", type: "select", default: "obsidian-gold", description: "3D theme finish preset", required: false, options: ["obsidian-gold", "monochrome-titanium", "cyberpunk-neon", "emerald-matrix", "midnight-amethyst"] },
      { name: "statusBadge", type: "string", default: "AVAILABLE FOR HIRE", description: "Availability pill text", required: false },
      { name: "showClock", type: "boolean", default: true, description: "Display live local time & timezone", required: false },
      { name: "cornerAccent", type: "boolean", default: true, description: "Display AdGrid signature 3D corner overshooting lines", required: false },
    ],
  },
  {
    name: "Sidebar",
    slug: "sidebar",
    category: "animated",
    description: "Sleek, modern slide-out website navigation sidebar for web applications and dashboards with expandable dashboard sub-menu options and DM Sans typography.",
    dependencies: ["framer-motion", "lucide-react"],
    packagePath: "animated/Sidebar.tsx",
    files: ["animated/Sidebar.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "isOpen", type: "boolean", default: true, description: "Controlled visibility open state of the sidebar drawer", required: false },
      { name: "onClose", type: "() => void", description: "Callback fired when closing sidebar via backdrop or escape key", required: false },
      { name: "side", type: "select", default: "left", description: "Docking edge placement on screen", required: false, options: ["left", "right"] },
      { name: "inline", type: "boolean", default: false, description: "Renders inline within container instead of fixed screen drawer", required: false },
      { name: "children", type: "React.ReactNode", description: "Custom navigation links and sidebar body elements", required: false },
      { name: "className", type: "string", description: "Additional custom class names for the sidebar container", required: false },
    ],
  },

  {
    name: "Command Palette",
    slug: "command-palette",
    category: "animated",
    description: "Tactile 3D skeuomorphic command palette modal (Cmd+K) featuring debossed search wells, raised tactile keycaps, clean monochrome styling, and smooth keyboard navigation.",
    dependencies: ["framer-motion", "lucide-react"],
    packagePath: "animated/CommandPalette.tsx",
    files: ["animated/CommandPalette.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "isOpen", type: "boolean", default: true, description: "Controlled open visibility of the quick action modal", required: false },
      { name: "onClose", type: "() => void", description: "Callback fired when palette closes via escape or backdrop click", required: false },
      { name: "placeholder", type: "string", default: "Type a command or search...", description: "Search input placeholder text", required: false },
      { name: "inline", type: "boolean", default: false, description: "Renders inline inside container instead of fixed screen overlay modal", required: false },
      { name: "items", type: "CommandItem[]", description: "Custom command items array with titles, icons, and keyboard shortcuts", required: false },
      { name: "className", type: "string", description: "Custom classes for command palette chassis", required: false },
    ],
  },
  {
    name: "Switch",
    slug: "switch",
    category: "animated",
    description: "Mechanical 3D rocker switch with realistic light/shadow elevation flips, integrated glowing LED indicator dot, and rebound spring physics.",
    dependencies: ["framer-motion"],
    packagePath: "animated/Switch.tsx",
    files: ["animated/Switch.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "checked", type: "boolean", default: true, description: "Controlled switch toggle state", required: false },
      { name: "disabled", type: "boolean", default: false, description: "Disable switch interaction", required: false },
      { name: "size", type: "select", default: "md", description: "Switch size variant", required: false, options: ["sm", "md", "lg"] },
      { name: "label", type: "string", default: "Security Protocol", description: "Switch label text", required: false },
      { name: "description", type: "string", default: "Enable 2FA Hardware Shield", description: "Switch description subtext", required: false },
    ],
  },
  {
    name: "OTP Component",
    slug: "otp-input",
    category: "animated",
    description: "Laser Vault PIN keypad and cell array featuring debossed input sockets, digit slot entry flash, red laser error shake, and green success unlock reveal.",
    dependencies: ["framer-motion", "lucide-react"],
    packagePath: "animated/OTPInput.tsx",
    files: ["animated/OTPInput.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "length", type: "number", default: 6, min: 4, max: 8, step: 1, description: "Number of verification digit PIN slots", required: false },
      { name: "correctPin", type: "string", default: "777777", description: "Pre-configured validation passcode", required: false },
      { name: "value", type: "string", description: "Controlled passcode string value", required: false },
      { name: "onChange", type: "(val: string) => void", description: "Callback triggered whenever digit input value changes", required: false },
      { name: "onComplete", type: "(val: string) => void", description: "Callback fired immediately when all PIN digits are filled", required: false },
      { name: "className", type: "string", description: "Custom container classes", required: false },
    ],
  },
  {
    name: "Tooltip",
    slug: "tooltip",
    category: "animated",
    description: "Magnetic Hologram Tooltip featuring 3D parallax tracking with mouse cursor position, glowing neon border, and frosted glass backdrop blur.",
    dependencies: ["framer-motion"],
    packagePath: "animated/Tooltip.tsx",
    files: ["animated/Tooltip.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "content", type: "React.ReactNode", description: "Tooltip popover body content or label", required: true },
      { name: "children", type: "React.ReactNode", description: "Trigger element that reveals the tooltip on pointer hover", required: true },
      { name: "side", type: "select", default: "top", description: "Anchor positioning side relative to the trigger", required: false, options: ["top", "bottom", "left", "right"] },
      { name: "align", type: "select", default: "center", description: "Alignment along side axis", required: false, options: ["start", "center", "end"] },
      { name: "delay", type: "number", default: 150, min: 0, max: 1000, step: 50, description: "Hover reveal delay before appearing in milliseconds", required: false },
      { name: "className", type: "string", description: "Additional classes for tooltip balloon container", required: false },
    ],
  },
  {
    name: "Timeline",
    slug: "timeline",
    category: "animated",
    description: "Circuit Path Timeline featuring traveling laser light pulses along connecting circuit lines and illuminated 3D debossed milestone node checkpoints.",
    dependencies: ["framer-motion", "lucide-react"],
    packagePath: "animated/Timeline.tsx",
    files: ["animated/Timeline.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "steps", type: "StepItem[]", description: "Array of step objects containing title, description, timestamp, and status", required: false },
      { name: "currentStep", type: "number", default: 2, min: 0, max: 6, step: 1, description: "Controlled active step index (0-indexed)", required: false },
      { name: "onStepChange", type: "(step: number) => void", description: "Callback fired when user clicks a step node", required: false },
      { name: "className", type: "string", description: "Additional wrapper classes", required: false },
    ],
  },
  {
    name: "Globe",
    slug: "globe",
    category: "animated",
    description: "A minimal monochrome 3D WebGL globe powered by cobe. Dark obsidian sphere with high-resolution world map sampling, atmospheric glow, and smooth drag rotation.",
    dependencies: ["cobe"],
    packagePath: "animated/Globe.tsx",
    files: ["animated/Globe.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "className", type: "string", description: "Additional classes for WebGL canvas container", required: false },
    ],
  },
  {
    name: "Bento Grid",
    slug: "bento-grid",
    category: "animated",
    description: "A dark Bento Grid with Inter typography, unboxed brand icons, and beveled or radiant card variants.",
    dependencies: ["framer-motion", "devicons-react"],
    packagePath: "animated/BentoGrid.tsx",
    files: ["animated/BentoGrid.tsx"],
    presentationStrategy: "center",
    propDefs: [
      {
        name: "variant",
        type: "select",
        default: "beveled",
        description: "Bento card visual style variant",
        required: false,
        options: ["beveled", "radiant"],
      },
    ],
  },
  {
    name: "Toast",
    slug: "toast",
    category: "animated",
    description: "A tactile beveled notification toast with a red dismiss control and reduced-motion-aware entrance and exit animation.",
    dependencies: ["framer-motion"],
    packagePath: "animated/Toast.tsx",
    files: ["animated/Toast.tsx"],
    presentationStrategy: "fullscreen",
    propDefs: [
      { name: "title", type: "string", default: "System Notification", description: "Primary toast alert headline text", required: true },
      { name: "description", type: "string", default: "Component copied to clipboard.", description: "Secondary message text", required: true },
      { name: "onDismiss", type: "() => void", description: "Callback fired when dismiss button is clicked or timer expires", required: true },
      { name: "stackDepth", type: "number", default: 0, min: 0, max: 4, step: 1, description: "Z-index stack position layer behind front toast", required: false },
      { name: "isExpanded", type: "boolean", default: false, description: "Whether notification stack expands on hover or focus", required: false },
      { name: "className", type: "string", description: "Custom styling classes", required: false },
    ],
  },
  {
    name: "Meter",
    slug: "meter",
    category: "animated",
    description: "Minimalist precision sentiment meter & gauge with automatic mount sweep calibration, dynamic sentiment colors, and real-time synchronized numerical counter.",
    dependencies: ["framer-motion"],
    packagePath: "animated/Meter.tsx",
    files: ["animated/Meter.tsx"],
    presentationStrategy: "center",
    propDefs: [
      { name: "value", type: "number", default: 45, description: "Score value (-100 to 100)", required: true, min: -100, max: 100, step: 5 },
    ],
  },
];


